### ISSUE TITLE
base url config

### ISSUE THREAD

**Issue by 2yearsmanong** [apache/incubator-answer#1008]
I want to differentiate multiple answer communities through nginx by using a domain name and URL
### To Reproduce
I changed the REACT.APP_BASE.URL through the. env.production under the UI package, but after the modification, it kept redirecting 50x.

### Expected behavior
![1720094447933](https://github.com/apache/incubator-answer/assets/174709266/ea0bf322-1610-4048-89d1-dc115ccaa88e)

![69d8781f-371a-41f3-8746-1da45259d82f](https://github.com/apache/incubator-answer/assets/174709266/95160218-3880-4186-878e-ed401afba4ac)

![17608a23-c842-4f82-8d0a-aea1751a9ad8](https://github.com/apache/incubator-answer/assets/174709266/62e5b95c-7fa0-4275-8a00-29e8929a87d4)

![f936ba61-c060-453b-a600-f41fae17cae0](https://github.com/apache/incubator-answer/assets/174709266/0529e8b4-e8c4-4dea-9adf-19990babe7cc)

### Screenshots
May I ask the author, what else do I need to configure a secondary domain name，Thank you
### Platform

- Device: [Desktop]
- OS: [windows]
- Browser and version: [Chrome]
- Version: [e.g. v1.3.5]

**Comment by shuashuai** [comment]
You can refer to this document: https://answer.apache.org/docs/deploy-subdirectory.

If you still have problems after trying it, you can continue to give feedback.

**Comment by 2yearsmanong** [comment]
Run the command Initialize the project, note that you need to add your base_url ([http://localhost:80/{base_url}/install/](http://localhost/%7Bbase_url%7D/install/)) to the access path here to see if the configuration is successful.INSTALL_PORT=80 . /answer init -C . /answer-data/.Is there a tutorial on how to add it to the access path when I initialize the third step? INSTALL_PORT=9080 REACT_APP_BASE_URL_PATH=/foo ./answer init -C ./answer-data/？thank you

**Comment by shuashuai** [comment]
You can look at it in conjunction with this document: https://answer.apache.org/docs/installation.

Normally, after the initialization command completes, the access address should be `localhost:80/install`, but if you change the value of base_url, the access address should be `http://localhost:80/base_url/install`, all you need to do here is manually splice in the access address, the actual configuration should be [done here](https://answer.apache.org/docs/installation#step-4-fill-in-basic-information)

**Comment by 2yearsmanong** [comment]
If my base_URL is/foo, what command should I use to initialize it?

**Comment by shuashuai** [comment]
INSTALL_PORT=80 . /answer init -C . /answer-data/

**Comment by 2yearsmanong** [comment]
Don't you need to add base_URL here? Can I access it directly through localhost/foo/install after initialization?

**Comment by shuashuai** [comment]
> Don't you need to add base_URL here?

No, it's just a startup command. base_url is for injecting paths when building static resources in the front end.

>Can I access it directly through localhost/foo/install after initialization?

Yes!

**Comment by 2yearsmanong** [comment]
There was an issue with the reverse proxy
Problem：no data
![1720363681463](https://github.com/apache/incubator-answer/assets/174709266/578d6cd1-79ca-41da-bebd-2f23ff4530c7)
Nginx
![1720364479600](https://github.com/apache/incubator-answer/assets/174709266/f2097410-c32b-438d-929a-5001797a6e65)
Info
![1720363973870](https://github.com/apache/incubator-answer/assets/174709266/5c60cfed-a68f-4931-98c5-04b5edb619a2)
code config
![code](https://github.com/apache/incubator-answer/assets/174709266/f6e84dea-95c4-4f10-808c-8d8e74c116b0)
May I ask what the problem is and if there are any further modifications needed.Thank you

**Comment by shuashuai** [comment]
From your Nginx configuration, you don't have proxy api related configuration, so api_url should be ingested as default, you can also look at the network request from the console, and then manually remove the api_url prefix to manually request for testing.

**Comment by C4T4** [comment]
same issue here
