### ISSUE TITLE
Support for pre-fill forms on the ask page

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#1009]
## Is your feature request related to a problem? Please describe

As mentioned in #252, we need some pre-fill support when ask question.

## Describe the solution you'd like

When visiting a link with a pre-fill parameter, the form content will be automatically filled.

Link: `/questions/ask?prefill={{ markdown_parameter }}`

`{{ markdown_parameter }}`:

```markdown
---
title: hello world
tags: feature-request, template
---

Some body text...

```

Result:

![image](https://github.com/apache/incubator-answer/assets/360618/503a0f98-1f46-4c0f-8234-6883f6f04943)

**Comment by hgaol** [comment]
Hi @fenbox , I'd like to try this task, thx! BTW, do we need the functionality of adding, updating, getting and deleting of question template?

**Comment by fenbox** [comment]
Hi @hgaol, the function of managing templates can be implemented by plugins in the future, which is not part of the core program.

**Comment by hgaol** [comment]
Hi @fenbox and @shuashuai , how about using json format for `{{ markdown_parameter }}`. e.g.
```json
{
  "tags": [],
  "title": "title",
  "content": "Hello World",
  ...
}
```

Cause I found it's not easy to parse markdown to get the metadata like tags, title. Pls let me know if any suggestion.

**Comment by shuashuai** [comment]
> Hi @fenbox and @shuashuai , how about using json format for `{{ markdown_parameter }}` and keep the same structure with draft in local storage. e.g.
> 
> ```json
> {
>   "tags": [],
>   "title": "title",
>   "content": "Hello World",
>   ...
> }
> ```
> 
> Cause I found it's not easy to parse markdown to get the metadata like tags, title. Pls let me know if any suggestion.

From a technical point of view, this is indeed the case. Using json is more intuitive and easier to parse.

**Comment by fenbox** [comment]
I prefer markdown because there are already typical system cases.

- There are two types of issue templates on GitHub: one is in markdown text format, and the other is in YAML configuration form. https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
- The case of dev.to is [markdown](https://dev.to/new?prefill=---%0Atitle%3A%20%0Apublished%3A%20false%0Atags%3A%20frontendchallenge%2C%20devchallenge%2C%20css%0A---%0A%0A_This%20is%20a%20submission%20for%20DEV%20Challenge%20v24.03.20%2C%20CSS%20Art%3A%20Favorite%20Snack._%0A%0A%23%23%20Inspiration%20%0A%3C%21--%20What%20snack%20are%20you%20highlighting%20today%3F%20--%3E%0A%0A%23%23%20Demo%0A%3C%21--%20Show%20us%20your%20CSS%20Art!%20You%20can%20directly%20embed%20an%20editor%20into%20this%20post%20(see%20the%20FAQ%20section%20of%20the%20challenge%20page)%20or%20you%20can%20share%20an%20image%20of%20your%20project%20and%20share%20a%20public%20link%20to%20the%20code.%20--%3E%0A%0A%23%23%20Journey%0A%3C%21--%20Tell%20us%20about%20your%20process%2C%20what%20you%20learned%2C%20anything%20you%20are%20particularly%20proud%20of%2C%20what%20you%20hope%20to%20do%20next%2C%20etc.%20--%3E%0A%0A%3C%21--%20Team%20Submissions%3A%20Please%20pick%20one%20member%20to%20publish%20the%20submission%20and%20credit%20teammates%20by%20listing%20their%20DEV%20usernames%20directly%20in%20the%20body%20of%20the%20post.%20--%3E%0A%0A%3C%21--%20We%20encourage%20you%20to%20consider%20adding%20a%20license%20for%20your%20code.%20--%3E%0A%0A%3C%21--%20Don%27t%20forget%20to%20add%20a%20cover%20image%20to%20your%20post%20(if%20you%20want).%20--%3E%0A%0A%0A%3C%21--%20Thanks%20for%20participating!%20--%3E).
- Markdown format will be more convenient for operators in non-technical industries to maintain.

> [!NOTE]
> In the tag section, only existing tags can be input, and if a tag does not exist, it will not be displayed.

**Comment by shuashuai** [comment]
I agree with the above point of view. 

> The case of dev.to is [markdown](https://dev.to/new?prefill=---%0Atitle%3A%20%0Apublished%3A%20false%0Atags%3A%20frontendchallenge%2C%20devchallenge%2C%20css%0A---%0A%0A_This%20is%20a%20submission%20for%20DEV%20Challenge%20v24.03.20%2C%20CSS%20Art%3A%20Favorite%20Snack._%0A%0A%23%23%20Inspiration%20%0A%3C%21--%20What%20snack%20are%20you%20highlighting%20today%3F%20--%3E%0A%0A%23%23%20Demo%0A%3C%21--%20Show%20us%20your%20CSS%20Art!%20You%20can%20directly%20embed%20an%20editor%20into%20this%20post%20(see%20the%20FAQ%20section%20of%20the%20challenge%20page)%20or%20you%20can%20share%20an%20image%20of%20your%20project%20and%20share%20a%20public%20link%20to%20the%20code.%20--%3E%0A%0A%23%23%20Journey%0A%3C%21--%20Tell%20us%20about%20your%20process%2C%20what%20you%20learned%2C%20anything%20you%20are%20particularly%20proud%20of%2C%20what%20you%20hope%20to%20do%20next%2C%20etc.%20--%3E%0A%0A%3C%21--%20Team%20Submissions%3A%20Please%20pick%20one%20member%20to%20publish%20the%20submission%20and%20credit%20teammates%20by%20listing%20their%20DEV%20usernames%20directly%20in%20the%20body%20of%20the%20post.%20--%3E%0A%0A%3C%21--%20We%20encourage%20you%20to%20consider%20adding%20a%20license%20for%20your%20code.%20--%3E%0A%0A%3C%21--%20Don%27t%20forget%20to%20add%20a%20cover%20image%20to%20your%20post%20(if%20you%20want).%20--%3E%0A%0A%0A%3C%21--%20Thanks%20for%20participating!%20--%3E).

I also prefer this solution


pr #1014  This solution simplifies the implementation of the technology, but it can be significantly more difficult for the user to use.

> From a technical point of view, this is indeed the case. Using json is more intuitive and easier to parse.

I'm sorry, I wasn't thinking in terms of user usage.

**Comment by hgaol** [comment]
Good point, sure, I'll update #1014 to use markdown format.

**Comment by hgaol** [comment]
updated to support markdown format. It'll use `title` and `tags` metadata to pre-fill title and tags.
