### ISSUE TITLE
The color of the hyperlinks filled in the answers is difficult to distinguish from the background color.

### ISSUE THREAD

**Issue by TheDeathDragon** [apache/incubator-answer#1012]
## Is your enhancement request related to a problem? Please describe

When filling out answers, if the website theme is dark, the color of the hyperlinks filled in the answers is difficult to distinguish from the background color. It is simply too dark.

## Describe the solution you'd like

I suggest adding a color to `.cm-line span` for the theme color; it should be much better. I am currently using `#ff8080`.

## Describe alternatives you've considered

An alternative solution could be to adjust the background color instead, but adding a color to `.cm-line span` seems to be a more straightforward and effective approach.

**Comment by TheDeathDragon** [comment]
![before](https://github.com/apache/incubator-answer/assets/36260451/3479483b-421e-456b-8bda-1310b0ce4572)
![after](https://github.com/apache/incubator-answer/assets/36260451/5ddbb211-f15d-4bf5-94fc-e93e2bac2eb8)

**Comment by shuashuai** [comment]
This bug is confirmed and we will fix this issue in version 1.3.6. Now you can use custom css in `admin/css-html ` to adjust the style.
