### ISSUE TITLE
Admin able to update DisplayName of user

### ISSUE THREAD

**Issue by powdermouse** [apache/incubator-answer#1024]
## Is your feature request related to a problem? Please describe

We use SSO to log in, if the user is renamed in AD, the following changes must be made (otherwise a new user will be created):
email, username, displayname

## Describe the solution you'd like

It would be nice to change DisplayName from the admin interface.

Changing the display name, user name and email should also be possible via API.

## Describe alternatives you've considered

I (and the user) are currently making the changes manually and before the user logs in again, which is very error prone.

**Comment by sy-records** [comment]
With support for changing username and email in #980, do we need support for changing displayname? cc @fenbox

**Comment by fenbox** [comment]
@sy-records Yes, I agree.
