### ISSUE TITLE
对搜索的支持似乎不太友好

### ISSUE THREAD

**Issue by hmlu** [apache/incubator-answer#105]
**Describe the bug**
对搜索的支持似乎不太友好

**To Reproduce**
在搜索栏搜索问题或者回答中的关键词

**Expected behavior**
期望能从标题、问题、回答、评论所有维度中搜索到相关关键词的帖子

**Screenshots**
![image](https://user-images.githubusercontent.com/4734071/204697894-f8f51cb8-2bd4-4915-a95b-b8ed4a766218.png)

![image](https://user-images.githubusercontent.com/4734071/204699509-d6e15873-e97e-4189-a051-ef5c14b156c8.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 107.0.5304.121

**Comment by SuperSupeng** [comment]
Are there plans to implement semantic search?

**Comment by fenbox** [comment]
We support [elasticsearch](https://github.com/apache/incubator-answer-plugins/tree/main/search-elasticsearch) and [meilisearch](https://github.com/apache/incubator-answer-plugins/tree/main/search-meilisearch) now.

You can develop plugins to enhance search results.
