### ISSUE TITLE
See all questions

### ISSUE THREAD

**Issue by frafra** [apache/incubator-answer#1061]
## Is your feature request related to a problem? Please describe

I just upgraded from 1.3.1 to 1.3.5 and the homepage became mostly empty, since there is no much activity during the summer.

## Describe the solution you'd like

Wouldn't be better just to show all the questions with some kind of pagination?

## Describe alternatives you've considered

Since there has been a major change between 1.3.1 and 1.3.5 in how many discussions are shown, what about making that configurable?

**Comment by shuashuai** [comment]
Version 1.3.6 will be released soon. In this version, the home page will display the newest list by default.

**Comment by frafra** [comment]
Wouldn't be desirable to browse all the questions in chronological order?

**Comment by shuashuai** [comment]
> Wouldn't be desirable to browse all the questions in chronological order?

Newest is sorted in reverse chronological order.

**Comment by frafra** [comment]
> > Wouldn't be desirable to browse all the questions in chronological order?
> 
> Newest is sorted in reverse chronological order.

Sorry, I meant *all* questions, implying that there is no pagination, but there is actually: it is just that my instance has not enough questions to show the pagination controls :) Thanks.

**Comment by shuashuai** [comment]
> > > Wouldn't be desirable to browse all the questions in chronological order?
> > 
> > 
> > Newest is sorted in reverse chronological order.
> 
> Sorry, I meant _all_ questions, as I do not see any pagination in the default page of 1.3.5, but I guess it is due to the default view being "Active".

It's exactly what you said

**Comment by fenbox** [comment]
Please update to [v1.3.6](https://github.com/apache/incubator-answer/releases/tag/v1.3.6), we've fixed the issue。
