### ISSUE TITLE
When a question has only one answer and this answer is deleted, the question will not display in the unanswered list.

### ISSUE THREAD

**Issue by LinkinStars** [apache/incubator-answer#1062]
## Describe the bug

When a question has only one answer and this answer is deleted, the question will not display in the unanswered list.

### To Reproduce

Steps to reproduce the behaviour:

1. Ask a question. After that, it will be displayed in the unanswered list.
2. Answer the question. Then, it will be removed from the unanswered list.
3. Delete the answer.
4. The question will not be displayed in the unanswered list.

### Expected behaviour

The question will be displayed in the unanswered list when the question has no answer. 

### Screenshots

<img width="791" alt="image" src="https://github.com/user-attachments/assets/029c73db-e621-4fce-928f-d5edea598202">

### Platform

- Device: [e.g. Desktop, Mobile]
- OS: [e.g. macOS]
- Browser and version: [e.g. Chrome, Safari]
- Version: [e.g. v1.3.5]

**Comment by sosyz** [comment]
I expect to solve this problem. Please assign it to me.

**Comment by yardenshoham** [comment]
Fixed in https://github.com/apache/incubator-answer/pull/1063
