### ISSUE TITLE
The reaction in mobile phone is displayed incorrectly

### ISSUE THREAD

**Issue by shuashuai** [apache/incubator-answer#1064]
## Describe the bug
As shown in the screenshot below, the emoticons should line up.

![image](https://github.com/user-attachments/assets/63a9d424-a608-4937-8e40-a88ce855c5fb)

### Expected behavior
 the emoticons should line up.
 
![image](https://github.com/user-attachments/assets/5ce70cc1-8c4d-4f61-97cf-5837c6594a4e)

**Comment by SantiagoLiendro** [comment]
Hi, I would like to contribute

**Comment by SantiagoLiendro** [comment]
Sorry, sorry, I didn't want to go out, I was wrong.
