### ISSUE TITLE
There are extra characters in the html source code

### ISSUE THREAD

**Issue by shuashuai** [apache/incubator-answer#1066]
## Describe the bug
Right-clicking to inspect the source code reveals that there are extra characters in the indistinguishable tags

![image](https://github.com/user-attachments/assets/8b8073a1-9014-4432-b9ba-b9d3c47ae60c)

### To Reproduce

1. Go to https://meta.answer.dev
2. Right-clicking to inspect the source code.
3. The URLs of og:image and twitter:image in meta have extra characters

### Expected behavior
Remove extraneous erroneous characters `}`.

### Platform

- Device: [e.g. Desktop, Mobile]
- OS: [e.g. macOS]
- Browser and version: [e.g. Chrome, Safari]
- Version: [e.g. v1.3.6]

**Comment by sosyz** [comment]
Hi, how is the frontend of [meta.answer.dev](meta.answer.dev) built and deployed? I tried to start using pnpm and compile static files, but the content is different.
<img width="1617" alt="image" src="https://github.com/user-attachments/assets/8e0375c1-c5db-4edb-a89d-71c385ee57ea">

**Comment by shuashuai** [comment]
Hi @sosyz 

Answer To meet the needs of SEO, in addition to the construction method you used above, there is also a set of back-end template files. This problem is because the content in the template file is wrong, so the method you used above cannot be seen. These can be seen under the `ui/template/header.html` file

**Comment by sosyz** [comment]
> Hi @sosyz
> 
> Answer To meet the needs of SEO, in addition to the construction method you used above, there is also a set of back-end template files. This problem is because the content in the template file is wrong, so the method you used above cannot be seen. These can be seen under the `ui/template/header.html` file

Thank you for your reply. I have modified the file and will submit a pull request later.

**Comment by yardenshoham** [comment]
Fixed in https://github.com/apache/incubator-answer/pull/1073
