### ISSUE TITLE
Help: SMTP Email is not notifying the @mention person

### ISSUE THREAD

**Issue by lovestaco** [apache/incubator-answer#1106]
I have set up SMTP and I am able to receive the email whenever there is a new question added.

But if somebody mentions my name in the comment, I don't get email, is the feature absent or am I missing something?

![image](https://github.com/user-attachments/assets/6f69a0c3-d6e3-47c9-9c8e-fbcf2ca1aa34)

**Comment by Haji001** [comment]
@lovestaco How were you able to configure/setup your **SMTP?** 

I have the application (apache answer) running in a docker container on a private ec2 instance however, I am not able to receive notification emails..

**Comment by lovestaco** [comment]
> @lovestaco How were you able to configure/setup your **SMTP?**
> 
> I have the application (apache answer) running in a docker container on a private ec2 instance however, I am not able to receive notification emails..

I created an IAM and setup SMT then went to the dashboard's https://dashboard.com/admin/smtp here I just entered the things and restarted, it started working.

@Haji001

**Comment by Haji001** [comment]
Fixed. It turns out that AWS block port 25 on ec2 by default. I had to open ticket with AWS support to open that port.
