### ISSUE TITLE
Combine Answer with Logto.

### ISSUE THREAD

**Issue by AllinProgram** [apache/incubator-answer#1108]
## Describe the bug

- [Apache Answer](https://github.com/apache/incubator-answer) is an effort undergoing incubation at The Apache Software Foundation.
- [Logto ](https://github.com/logto-io/logto)is an open-source Auth0 alternative designed for modern apps and SaaS products.
I hope to use Logto as the user center of Answer and provide authorization for Answer.

Logto provides OIDC, and Answer supports OAuth2.0.
I understand that OIDC is a superset of OAuth2.0, but when I use it together, it return an error. I wonder if these two great tools can be used together.
I have fully configured the information of Logto in Answer, so I can jump to the login page. After the login callback, this process returns invalid request information.

```log
ERROR	controller/connector_controller.go:130	connector received failed, error info: code exchange failed: oauth2: cannot fetch token: 400 Bad Request
Response: {"code":"oidc.invalid_request","message":"Request is invalid.","error":"invalid_request","error_description":"missing required parameter 'code'"}, response data is:
```

### To Reproduce

1. Open Logto and create a OIDC Application;
2. Set Logto info into Answer Oauth2.0 plugin;
3. Set [Answer callback uri](https://github.com/apache/incubator-answer-plugins/tree/main/connector-basic) into Logto;
4. Start Login, input correct account info and click login.
5. Wait callback, then log error info.

### Expected behavior

Login Success.

### Screenshots

Nan.

### Platform

- Device: [iPhone 15 Pro]
- OS: [ios]
- Browser and version: [Safari]
- Version: [v1.3.6]

### More
Thank you for your efforts to make such a great tool.
If you think this is not a bug of Answer, please give me some information to help me, and you can close this issue directly.
If you are interested in this scenario, I can provide Logto instance and Answer instance for your investigation.

**Comment by allinprogram** [comment]
@LinkinStars Thank you for your reply.
My current thinking direction is the same as what you described.🍻

But I successfully configured it in NodeBB (only supporting OAuth2.0).😢

Finally, Maybe I need a OIDC plugin in Answer.

**Comment by allinprogram** [comment]
After communicating with the other party, the other party pointed out that the problem lies in the agreement support. Have you considered supporting OIDC in the near future?

**Comment by AllinProgram** [comment]
@LinkinStars I realized I should have submitted an issue there. Thanks for reminding me. I will close the issue now.

Thank you for your patience.

**Comment by xiaoyijun** [comment]
Hi @AllinProgram , I just created an blog about this topic, hope it helps: [Logto in action: Integrate Apache Answer to launch a community for your users](https://blog.logto.io/logto-apache-answer).
