### ISSUE TITLE
v1.4.0 Error swagger config

### ISSUE THREAD

**Issue by AllinProgram** [apache/incubator-answer#1117]
## Describe the bug

https://github.com/apache/incubator-answer/blob/8e6fa13c72dae18b8c516bf349928f9d3109988c/docs/swagger.yaml#L2914

title should not add `""`. It make api doc can not be parse.

### To Reproduce

1. purge to install v1.4.0 by docker.
2. open [doc ](https://xxx.xxx/swagger/doc.json)
3. you will see two double quotes, error to parse json.

### Expected behavior

Nan
### Screenshots

![image](https://github.com/user-attachments/assets/be85f987-e414-4e14-858f-d2a650b3c25d)
### Platform
Nan

**Comment by AllinProgram** [comment]
If you confirm this is an obvious issue, I'd be very inclined to submit a PR.

**Comment by sy-records** [comment]
The dev branch has been fixed, I'm not sure it needs to be re-released for v1.4.0. cc @robinv8 
https://github.com/apache/incubator-answer/blob/48c238785359238d1ed278dd0921476d4ebd4c66/docs/swagger.yaml#L2913

**Comment by AllinProgram** [comment]
@sy-records Thanks, I got it.
Hope to release it soon, thank you for your efforts.
