### ISSUE TITLE
When you enter tag letter, the dropdown flashes when you enter it

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#1118]
## Describe the bug

In ask page, when you enter each letter of the tag, the dropdown flashes when you enter it.

### To Reproduce

https://github.com/user-attachments/assets/6f3e7166-1322-46da-b41f-fb7779af03a4

### Expected behavior

During the type process, the dropdown results can be showed with an appropriate delay.

### Platform

- Device: Desktop
- OS: macOS
- Browser and version: Chrome
- Version: v1.4.0

**Comment by prithvidasgupta** [comment]
@fenbox Can I work on this?

**Comment by fenbox** [comment]
@prithvidasgupta Of course. Looking forward to it.
