### ISSUE TITLE
Remove the minimum username length restriction

### ISSUE THREAD

**Issue by hhhguany** [apache/incubator-answer#1124]
## Is your enhancement request related to a problem? Please describe

I use OAuth to connect accounts. Many users have 3-character usernames in the existing external account system, so is it possible to remove the minimum username length restriction.

## Describe the solution you'd like

Remove the minimum username length restriction.

## Describe alternatives you've considered

Set the minimum username length to 2.

**Comment by zahash** [comment]
i'll do this

**Comment by zahash** [comment]
here is the PR

https://github.com/apache/incubator-answer/pull/1127

**Comment by elquimista** [comment]
I tried the latest version (1.4.5) on Docker and username min length is still set to 4. @zahash

**Comment by sy-records** [comment]
@elquimista You can submit the reproduction step as a new issue.
