### ISSUE TITLE
Change list/unlist causes tag display exception

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#1144]
### To Reproduce

1. Unlist a question with two or more tag
2. Edit the question, remove one tag and add another one
3. List the question
4. The removed tag is re-displayed

### Expected behavior

Removed tags should not be displayed.

### Screenshots

https://github.com/user-attachments/assets/ddca691e-6c2b-4e0d-b2b6-229c402a1fae

**Comment by sosyz** [comment]
@fenbox Hi~
I've identified two issues. First, when restoring hidden tag relationships, we're not filtering out deleted data. Second, when updating questions, the tag relationships default to available status, without considering cases where the question might be hidden.
Please assign this to me, and I'll submit a pull request later.
