### ISSUE TITLE
local start backend ui always loading

### ISSUE THREAD

**Issue by chenyong0923** [apache/incubator-answer#1157]
## Describe the bug

code is latest

go mod download
go run cmd/answer/main.go init -C ./answer-data

[SUCCESS] answer installation service will run at: http://localhost:80/install/ 

but result is loading，not config UI

![image](https://github.com/user-attachments/assets/651e9b0e-0007-4b17-a390-50f6906d1764)

- Device: [e.g. Desktop, Mobile]
- OS: [e.g. macOS]
- Browser and version: [e.g. Chrome, Safari]
- Version: [e.g. v1.2.0]

**Comment by chenyong0923** [comment]
![image](https://github.com/user-attachments/assets/ebf95740-37ed-44b3-b53a-9a8864891f71)
build a new image, start by image is same

**Comment by chenyong0923** [comment]
![image](https://github.com/user-attachments/assets/df0a8873-cb90-4bf9-ad06-fba81ca4840c)

**Comment by sy-records** [comment]
You can refer to the documentation for installation: https://answer.apache.org/docs/installation

**Comment by chenyong0923** [comment]
> > ![image](https://private-user-images.githubusercontent.com/119842780/380628447-df0a8873-cb90-4bf9-ad06-fba81ca4840c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDU0NzEsIm5iZiI6MTczMDEwNTE3MSwicGF0aCI6Ii8xMTk4NDI3ODAvMzgwNjI4NDQ3LWRmMGE4ODczLWNiOTAtNGJmOS1hZDA2LWZiYTgxY2E0ODQwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQwODQ2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2VlNjNmNzM2NThkMDJhNTFiYjJmYTBlMWNmMzIzNjJjYjczYmUzOWQxOGEyMDM0YTI4OGQ1ODhiNzQ2YmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tLli20PKpcP2X-AOgBBT6YJhTsAoU3LXK80ivWIKbd8)
> 
> @chenyong0923 Maybe you need to compile frontend first. `make ui`

It's ok for me，but request redirect to 50x，how to config base_url ?
![image](https://github.com/user-attachments/assets/75dd59e8-73df-41cb-b541-02a4561a40b0)
![image](https://github.com/user-attachments/assets/37610787-2346-44c2-a78a-8dba70e49251)

**Comment by sy-records** [comment]
https://github.com/apache/incubator-answer/blob/main/ui/.env.development

**Comment by chenyong0923** [comment]
> https://github.com/apache/incubator-answer/blob/main/ui/.env.development

This is the path that the client configures for the server. Not work

**Comment by sy-records** [comment]
You need to configure it first to ensure that the UI has access to the correct backend service API.

**Comment by chenyong0923** [comment]
> You need to configure it first to ensure that the UI has access to the correct backend service API.

Not work，I'll outline the steps involved

1. make ui
2. cd ui, pnpm I & pnpm start (this REACT_APP_API_URL used default http://10.0.20.84:8080 or used http://127.0.0.1)
3. go run cmd/answer/main.go init -C ./answer-data
4. request http://localhost:80/install in browser (this is backend service)

**Comment by chenyong0923** [comment]
> You need to configure it first to ensure that the UI has access to the correct backend service API.

The problem is solved. After the server starts, it should access the front-end started service and enter the configuration page through the /install route, rather than access the service directly on the server side

Thanks
