### ISSUE TITLE
How to Deploy front-end 

### ISSUE THREAD

**Issue by chenyong0923** [apache/incubator-answer#1162]
Building a new image from the official Dockerfile creates a back-end service, right? Does the front-end service need to be deployed separately? When accessing the container's port through a browser, it keeps loading.

<img width="979" alt="image" src="https://github.com/user-attachments/assets/77c8f14b-ce16-4b98-8c57-47068e2b72c6">
<img width="1316" alt="image" src="https://github.com/user-attachments/assets/4ed1fea3-ba42-40cb-9a58-8ebd774958c7">

**Comment by chenyong0923** [comment]
When deploying to the production environment, you would first package the image, then deploy the backend, and then deploy the frontend via nginx, right?

**Comment by chenyong0923** [comment]
> @chenyong0923 First of all, for the whole project, the frontend doesn't need to be deployed separately. Just compile the frontend and then the backend, and finally package it into a docker image to start. Then just use the nginx proxy you mentioned to access the port of the container.

Now the mirrored boot has started, and the browser is trying to access the boot port, but it is not able to enter the install page normally. Why is that?

**Comment by sosyz** [comment]
@chenyong0923 Maybe you can use [storage-aliyunoss](https://github.com/apache/incubator-answer-plugins/tree/main/storage-aliyunoss) if you want to save files on OSS ?

**Comment by chenyong0923** [comment]
> @chenyong0923 Maybe you can use [storage-aliyunoss](https://github.com/apache/incubator-answer-plugins/tree/main/storage-aliyunoss) if you want to save files on OSS ?

Thanks，I mainly want to upload videos, does this plugin support video uploads? Or is it only for storing images on Oss? I have already implemented the local function, but the problem is that the rebuilt image service keeps loading.

**Comment by chenyong0923** [comment]
> @chenyong0923 If you haven't modified the dockerfile, then maybe the build should have a problem. First, you can try to build the frontend locally by `make ui` command. If there is no problem, then keep the output log when executing the `docker build` command to see if there are any error messages during the frontend build process.

I am currently doing it like this: first, I build the front-end make ui, then the back-end make build, both of which are working fine. Finally, I build the image.

<img width="520" alt="image" src="https://github.com/user-attachments/assets/22f617c6-04b3-4b94-a2f7-726a8ac544d9">

**Comment by chenyong0923** [comment]
> @chenyong0923 OK. Then it's very likely that there's a problem with the docker image build process.

Sometimes building an image may result in errors due to installation dependency issues, but even if an image is successfully built, there may still be issues.
<img width="1066" alt="image" src="https://github.com/user-attachments/assets/5cb29619-2c68-493c-928f-acf0835589c1">
<img width="1010" alt="image" src="https://github.com/user-attachments/assets/6afc637e-1a51-4107-b879-806f73be8295">

<img width="1169" alt="image" src="https://github.com/user-attachments/assets/0ab51e30-9fce-40fa-af15-669d51a52cfb">

**Comment by chenyong0923** [comment]
> @chenyong0923 Well, it looks like a network issue. 🤔

Yes, just keep trying, and you'll be able to build it successfully. However, when I build a successful image, the browser keeps loading the page, and this has been bothering me for a long time. I don't know what the cause is. Even when I build an image using the official main branch code, it also keeps loading.

**Comment by chenyong0923** [comment]
> > Even when I build an image using the official main branch code, it also keeps loading.
> 
> @chenyong0923 That's kind of weird. But you can try using the official image first. `docker pull apache/answer:latest`. If there is no problem, then there must be something wrong with the docker build process. Because the official image is built from the `dockerfile` in the code repository. The whole process is built using GitHub action with no human intervention.

It's normal to pull the official image directly from the Docker Hub, and cloning the official source code and building the image also results in a loading status. I will try it on another computer.

**Comment by chenyong0923** [comment]
> > Even when I build an image using the official main branch code, it also keeps loading.
> 
> @chenyong0923 That's kind of weird. But you can try using the official image first. `docker pull apache/answer:latest`. If there is no problem, then there must be something wrong with the docker build process. Because the official image is built from the `dockerfile` in the code repository. The whole process is built using GitHub action with no human intervention.

When will the official mirror image support the last video? This is a necessary requirement, so I have made a secondary development.

**Comment by chenyong0923** [comment]
> > Even when I build an image using the official main branch code, it also keeps loading.
> 
> @chenyong0923 That's kind of weird. But you can try using the official image first. `docker pull apache/answer:latest`. If there is no problem, then there must be something wrong with the docker build process. Because the official image is built from the `dockerfile` in the code repository. The whole process is built using GitHub action with no human intervention.

I found the problem, start the plug-in, the front-end route is lost, get the plug-in state, return undefined, need to add a backstory logic，return undefined, assign an empty array

<img width="1158" alt="image" src="https://github.com/user-attachments/assets/3ae6da1d-9a44-48b9-9aba-401c108d607d">
<img width="1009" alt="image" src="https://github.com/user-attachments/assets/d20cc2fe-2ebb-404c-afd3-8be70089f395">
<img width="525" alt="image" src="https://github.com/user-attachments/assets/51d394b3-275e-4da5-a4dc-792b090adb82">
<img width="707" alt="image" src="https://github.com/user-attachments/assets/16c823b9-898b-409f-a43f-b9c01b7a9b9d">

**Comment by shuashuai** [comment]
>I found the problem, start the plug-in, the front-end route is lost, get the plug-in state, return undefined, need to add a backstory logic，return undefined, assign an empty array

@chenyong0923  

I tested it, and it is indeed like this. It should be related to the adjustment of the routing logic of the last load of the socket. The number of interfaces allowed to be accessed when ignoring /install is limited, so there is a problem here during initialization. I will fix it, thanks for the feedback.
