### ISSUE TITLE
Tag summary display is not as expected on tag detail page

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#1169]
## Is your enhancement request related to a problem? Please describe

![image](https://github.com/user-attachments/assets/9e05c22c-b728-4904-83d8-786cb4fc2ccc)

On the tag details page, the tag summary display is not as expected.

## Describe the solution you'd like

![image](https://github.com/user-attachments/assets/240b8e3b-37cb-441d-b077-5d82a34c263c)

1. The summary presents the first description in markdown parsed.
2. Change the "More" link to a "Wiki" button.

**Comment by sy-records** [comment]
Summary used `escapeRemove` to remove html, need to do retention?

**Comment by shuashuai** [comment]
> > Summary used `escapeRemove` to remove html, need to do retention?
> 
> @shuashuai If we want the description to show the parsed markdown, don't we need to use the `escapeRemove` method or not?

There is no need to use it after the requirements change. According to the new features, it is necessary to display and correctly parse html.
