### ISSUE TITLE
Deleted file should not be seen in sitemap

### ISSUE THREAD

**Issue by lhui** [apache/incubator-answer#1212]
## Describe the bug

I used the management end to delete preset articles and comments, but in the sitemap, I can still see the deleted files and they are still visible. This deletion function has become an archiving function.

### To Reproduce

1. Go to Setting -> Admin -> Contents -> Questions
2. Click on Item 's 'Action' Delete
3. Go to > Contents -> Answers
4. Click on Item 's 'Action' Delete
5. Go to  sitemap.xml

### Expected behavior

deleted file should not be seen in sitemap.xml

### Screenshots

<img width="1437" alt="image" src="https://github.com/user-attachments/assets/fd8ceb99-7bbe-44f5-b7ac-6cab66534898" />

sitemap.xml

<img width="1492" alt="image" src="https://github.com/user-attachments/assets/37aaea7c-9ed0-4f3a-88f8-fd77f9c3c6ee" />

### Platform

- Device: Desktop
- OS:  macOS
- Browser and version: Chrome
- Version: 1.4.1

**Comment by sy-records** [comment]
Thank you for your feedback.

The sitemap has a 1 hour cache by default, so when you delete it the results are not up to date.

**Comment by lhui** [comment]
Thank you. The problem has been solved after one hour.
