### ISSUE TITLE
Dark Mode Support

### ISSUE THREAD

**Issue by mariushosting** [apache/incubator-answer#168]
Answer should support Dark Mode. Add an option to Switch the theme from light to dark and viceversa will improve UI for all people.

**Comment by fenbox** [comment]
Thank you for your advice.

Answer's default theme based on bootstrap 5.2. [Bootstrap 5.3.0-alpha1 version](https://blog.getbootstrap.com/2022/12/24/bootstrap-5-3-0-alpha1/) brings dark mode support a few weeks ago. We are plan to support dark mode after bootstrap v5.3 stable version release.

**Comment by mariushosting** [comment]
> Thank you for your advice.
> 
> Answer's default theme based on bootstrap 5.2. [Bootstrap 5.3.0-alpha1 version](https://blog.getbootstrap.com/2022/12/24/bootstrap-5-3-0-alpha1/) brings dark mode support a few weeks ago. We are plan to support dark mode after bootstrap v5.3 stable version release.

Awesome 👍😎 Thank you for the prompt answer!

**Comment by mariushosting** [comment]
@fenbox Any news about this? Bootstrap 5.3.0 is out?

**Comment by fenbox** [comment]
@mariushosting In the plan now.

**Comment by mariushosting** [comment]
> @mariushosting In the plan now.

Awesome!!! Just awesome!

**Comment by grand-lotus-iroh** [comment]
Agreed. Can't wait! Maybe something similar to "follow system" like I've seen in https://github.com/usememos/memos in their admin options... excited!
