### ISSUE TITLE
Need attachment-upload feature

### ISSUE THREAD

**Issue by coanor** [apache/incubator-answer#211]
**Is your feature request related to a problem? Please describe.**
Sometimes we have to upload large-text-file(such as large-HTTP-response/large-logging) to questions. If we put these text within qustion description, it makes we hard to read the core question text.

**Describe the solution you'd like**
Just like add attachment to email.

**Describe alternatives you've considered**
I think add-attachment is the most popular manner, or we have to make another CDN like to store these files.

**Comment by sosyz** [comment]
@fenbox Hi~
I have some ideas regarding this issue. Perhaps we could develop a package to manage files? This package would support local storage or storage on S3, allow for duplicate file processing, and could serve as a foundational package for development related to #300.

**Comment by fenbox** [comment]
@sosyz We can use the [Kano Model](https://en.wikipedia.org/wiki/Kano_model) to analyze the "files management package". I think it's not a Must-be or One-dimensional requirements. So this feature is not suitable as a core feature.

But there are some users who need this feature, so it's suitable as a plugin.

**Comment by sosyz** [comment]
> @sosyz We can use the [Kano Model](https://en.wikipedia.org/wiki/Kano_model) to analyze the "files management package". I think it's not a Must-be or One-dimensional requirements. So this feature is not suitable as a core feature.
> 
> But there are some users who need this feature, so it's suitable as a plugin.

@fenbox Got it, I agree with your perspective. Implementing it as a plugin would indeed be a better approach.
