### ISSUE TITLE
How to upload attachments?

### ISSUE THREAD

**Issue by ghost** [apache/incubator-answer#273]
![Screenshot_2023-03-22-23-06-37-848_com microsoft emmx-edit](https://user-images.githubusercontent.com/32785798/226959506-7d5601ed-1bc8-412d-aabc-5b63b026a9b5.jpg)

提问或者回答时，在哪里可以上传附件？如果目前不支持，希望能增加此功能。

**Comment by fenbox** [comment]
Currently we do not support attachment upload.

**Comment by fenbox** [comment]
Same as #211
