### ISSUE TITLE
Add support for parametrizing the base path

### ISSUE THREAD

**Issue by borjapazr** [apache/incubator-answer#335]
**Is your feature request related to a problem? Please describe.**
Currently, the application does not allow users to parametrize the base path, which makes it difficult to configure a reverse proxy with path routing. This lack of flexibility can hinder deployment in certain scenarios and configurations.

**Describe the solution you'd like**
Please add support for parametrizing the base path within the application's configuration. This feature would enable users to set up a reverse proxy with path routing more easily and allow for seamless integration with various deployment environments. Ideally, this should be done in a way that doesn't break existing configurations.

**Describe alternatives you've considered**
I have considered using URL rewriting to work around this limitation, but it's less efficient and can potentially cause issues with certain configurations.

**Additional context**
The ability to parametrize the base path is a common feature in many web applications and would greatly improve the flexibility and ease of deployment for the `answer` application. By supporting this feature, we can ensure that the application remains adaptable to a variety of infrastructures and configurations.

**Comment by gilly42** [comment]
Would be great. Please build.
