### ISSUE TITLE
How to apply keyword sensorship?

### ISSUE THREAD

**Issue by TLMROBIN** [apache/incubator-answer#368]
As we all know，there are certain topic cannot be discussed in China. Is there a wey to apply keyword sensorship to every  question and answer? 

we wanna apply it in a middle school student community. The content they put on it must be under control.

**Comment by surapuramakhil** [comment]
This one looks similar to this https://github.com/apache/incubator-answer-plugins/issues/81

**Comment by surapuramakhil** [comment]
Working of will be exactly the same, but what you block differs.
