### ISSUE TITLE
API interface for gpt-based quick q/a fill-ups

### ISSUE THREAD

**Issue by ciaovention** [apache/incubator-answer#386]
**Is your feature request related to a problem? Please describe.**
API interface for gpt-based quick q/a fill-ups

**Describe the solution you'd like**
If (there is already an api system, used for adding questions, making answers, pull all questions and etc): can these API be openly used with an access_token or username/psw etc, from a local or access-origin-allowed url.
If (there isn't such thing or it's not safe enough to release the apis as of now): can someone post dev. instructions so that we can build on top of it.

**Describe alternatives you've considered**
typical usage: a gpt-pass-along server can get conversation lists and make qa pairs according to the conversations, we'd like to keep them in answers, and fine-tune according to answer sites' human answers further.

**Comment by Tantyee** [comment]
Nice feature!

**Comment by fenbox** [comment]
API document is [here](https://answer.apache.org/docs/api)
