### ISSUE TITLE
Display github icon & username in UserInfo

### ISSUE THREAD

**Issue by conr2d** [apache/incubator-answer#435]
**Is your feature request related to a problem? Please describe.**

Currently, the website in user info page shows the domain name of user's website.

**Describe the solution you'd like**

If user's website is hosted on a well-known service like github, it would be good if it can show the service icon and username like `@conr2d`.

**Describe alternatives you've considered**

Customizing additional user info items can be provided as a feature of administration.

**Comment by fenbox** [comment]
The current temporary solution is to write GitHub information in the "about me" section.

**Comment by AdityaMayukhSom** [comment]
The solutions I propose are as follows -

1. Pattern match the website URL with well knows hosting providers and conditionally render the corresponding icons. 
[Relevant code in repository](https://github.com/apache/incubator-answer/blob/da490d4006281376313abd984a0e75450d6e9041/ui/src/pages/Users/Personal/components/UserInfo/index.tsx#L125)
    #### Implementation details: 
    In the above code, the icon name needs to be changed conditionally.

2.  In case of GitHub hosting, GitHub username can be found from the URL (As far as I understand the subdomain section of `github.io` in the website URL should work).
[Relevant code in repository](https://github.com/apache/incubator-answer/blob/da490d4006281376313abd984a0e75450d6e9041/ui/src/pages/Users/Personal/components/UserInfo/index.tsx#L99)
    #### Implementation details: 
    We can add a `div` below the existing `data.username` and create a GitHub page link by concatenating  github username with githul base URL. We can additionally give the user the option to add custom GitHub profile URL instead of the one fetched from website, in case the website is hosted on some other GitHub account, for any particular reason, or disable the feature of extracting GitHub from website URL.

Please share your thoughts and feedback on these. If approved, I'm ready to proceed with implementation.
