### ISSUE TITLE
Images in the private mode can still be accessed when not logged in

### ISSUE THREAD

**Issue by zhenruyan** [apache/incubator-answer#502]
私有状态下图片仍然可以在非登录状态下访问。
设置成必须登录才能查看后，图片仍然可以直接访问。

**Comment by fenbox** [comment]
这里带来一个问题，如果图片存在第三方 OSS，该如何验证权限呢？

Here is a question: how to verify the permission of images if they are stored in OSS (Object Storage Service)?

**Comment by zhenruyan** [comment]
参考minio和七牛云又拍云等的方案，通常是向oss服务申请一个key ，再通过303重定向到真实的带着key的资源链接实现的。
但这会带来一系列的问题，比如问题内容发布修改时的逻辑。 以及图片资源需要归档到数据库等。
具体参考文档  https://help.upyun.com/knowledge-base/cdn-token-limite/
（通常客户端会这么干 ，不知道老哥有没有什么骚操作）

Referring to solutions such as Minio and Qiniuyun Youpaiyun, it is usually achieved by applying for a key from the OSS service and redirecting it to a real resource link with the key through 303.

But this will bring a series of problems, such as the logic when publishing and modifying the problem content. And image resources need to be archived in the database.

Specific reference documents https://help.upyun.com/knowledge-base/cdn-token-limite/

**Comment by carlqt** [comment]
This sounds like an interesting problem. I'd like to help out but since I'm very new and unfamiliar with the App, can someone provide a "steps to replicate" instruction so I can get started quickly?

**Comment by carlqt** [comment]
Thanks @LinkinStars , I'm able to run the app in my local but was wondering if there's documentation/steps on how to replicate this exact scenario or the url/route of this specific feature?

If not, I will just explore and see if I can find it 👌

**Comment by carlqt** [comment]
Got it. I think I will just look for other issues that I can help out then.

I'd like to help with the discussion but I'm not sure exactly what the bug is. From my understanding, the reporter has set their uploaded image to "private" but it's still viewable for unauthenticated users.

**Comment by AionKwong** [comment]
现在有一个新问题。当设置为私有后，登录用户后，用户上传的图片无法预览。

**Comment by AionKwong** [comment]
> 对不起，让我确认一下。因此，请清除浏览器缓存，注销，然后重新登录并刷新页面。

这个问题还是存在，是否和安装的版本有关？ 我这边是使用最新的docker镜像进行安装。

**Comment by AionKwong** [comment]
是直接使用ip访问的。
[1Panel-answer-h3Zj-20231120163702.log](https://github.com/apache/incubator-answer/files/13408454/1Panel-answer-h3Zj-20231120163702.log)

**Comment by fenbox** [comment]
Fixed in v1.2.0
