### ISSUE TITLE
Paste from Clipboard (also support .webp, png, gif, etc format)

### ISSUE THREAD

**Issue by grand-lotus-iroh** [apache/incubator-answer#530]
When I copy an image to my clipboard, it would be convenient to simply use CTRL + V to paste it into the post. Currently, I need to either press CTRL + G or use the icon to insert the image if I prefer not to drag and drop.

![image](https://github.com/answerdev/answer/assets/1291364/610aeb62-3c9f-4a95-bf7b-5d78c19eb171)

**Comment by fyzhu** [comment]
png & jpeg is supported
webp & gif is not supported
and if you paste a not supported file, the editor is not responding any more

**Comment by fenbox** [comment]
Fixed in v1.2.0
