### ISSUE TITLE
Allow admin can disable the default log in form

### ISSUE THREAD

**Issue by fame-odoo** [apache/incubator-answer#565]
**Is your feature request related to a problem? Please describe.**
Hello there, I have been self-hosting answer.dev for a while and in order to enhance the security I am thinking of to disable the default log in form, only use the oauth log in.

**Describe the solution you'd like**
I would like a toggle option in settings page for the admin that we can disable the default log in form.

**Describe alternatives you've considered**
n/a

**Comment by fenbox** [comment]
Thank you for your advice.

Disable password login is a dangerous option, and we also need to consider the option of recovery when it is closed by mistake.

**Comment by jihuayu** [comment]
We can consider not disabling the password login functionality for administrators. Or we can choose not to disable password login for specific IP addresses, such as "localhost."

**Comment by ignatz** [comment]
+1 to the request.

Just to add to the list of options: relegate the default password login to an additional/alternative non-public path.
