### ISSUE TITLE
It can be difficult to distinguish between answers and comments

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#575]
**Describe the bug**

When there is a lot of content, it can be difficult to distinguish between answers and comments.

![image](https://github.com/apache/incubator-answer/assets/360618/8c04703c-0f52-4051-bba7-ef56d7da649b)

**Expected behavior**

Need to differentiate comments section more, such as adding a background color to the comments section.

**Comment by niranjan-kurhade** [comment]
Hey @fenbox , I would like to work on this issue. Please assign it to me.

**Comment by fenbox** [comment]
@niranjan-kurhade Thank you for your participation. Here is the [design files](https://www.figma.com/file/MeOkbCEQS9jCDRVHcjTRtY/Answer-Core?type=design&node-id=250%3A616&mode=design&t=JrVtJj2ixXnU6gpG-) based on the [bootstrap specification](https://getbootstrap.com/docs/5.3/getting-started/introduction/). Looking forward to it

**Comment by niranjan-kurhade** [comment]
> @niranjan-kurhade Thank you for your participation. Here is the [design files](https://www.figma.com/file/MeOkbCEQS9jCDRVHcjTRtY/Answer-Core?type=design&node-id=250%3A616&mode=design&t=JrVtJj2ixXnU6gpG-) based on the [bootstrap specification](https://getbootstrap.com/docs/5.3/getting-started/introduction/). Looking forward to it

Thank you! @fenbox, I was thinking of these changes to differentiate-
- Make answers have a different background color than comments
- Use bold or larger font size for answers
- Right align comments and left align answers 
- Implement threading to nest comments under answers (Identing)

What do you think?

**Comment by fenbox** [comment]
@niranjan-kurhade Thank you for your advice. The design file you see is what we're about to expect to make changes to, and can be made without more complex changes.
