### ISSUE TITLE
fix typo - questionOperation

### ISSUE THREAD

**Issue by GlenCarpenter** [apache/incubator-answer#576]
https://github.com/apache/incubator-answer/blob/3e6a202d37e7a8f9d8749d656da240e1ab674104/ui/src/components/Operate/index.tsx#L15

This should probably be `questionOperation`, not `questionOpetation`

**Comment by rawatsushil** [comment]
is this issue open for contribution

**Comment by shuashuai** [comment]
Thanks for the feedback, we accept any form of contribution, and we will use some tools to check the spelling of words in the future. @rawatsushil  @GlenCarpenter

**Comment by GlenCarpenter** [comment]
> Thanks for the feedback, we accept any form of contribution, and we will use some tools to check the spelling of words in the future. @rawatsushil @GlenCarpenter

@shuashuai The misspelling was not the reason I reported, it was because further along in the file the variable was spelled differently which caused eslint to flag.  I think this will be caught during PRs moving forward since the github workflows will pre-build the UI package.
