### ISSUE TITLE
update website url

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#583]
Update website url to https://answer.apache.org in this repo description.

![image](https://github.com/apache/incubator-answer/assets/360618/ad7f52bf-a668-4221-a2d3-8f5081b2938d)

**Comment by tisonkun** [comment]
Please do not assign issues to others without proactive requesting. All contributors work in a volunteer bias instead of being assigned to finish the task as an employee.

**Comment by tisonkun** [comment]
While I'm of course glad to help and you can review https://github.com/apache/incubator-answer/pull/584 for how to do so. The `.asf.yaml` file is self-described for how to change repo settings.

**Comment by tisonkun** [comment]
> Please do not assign issues

Instead, you can ping someone you want to notify with `@id`.

**Comment by fenbox** [comment]
> > Please do not assign issues
> 
> Instead, you can ping someone you want to notify with `@id`.

Got it, understood.
