### ISSUE TITLE
tag search need support for synonyms 

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#587]
**Describe the bug**

https://meta.answer.dev/tags

I set "k8s" as a synonym for "kubernetes". When I search "k8s" in `/tags` page, there is no results.

**To Reproduce**

1. Go to `/tags`
2. Click on "filter by tag name", type `k8s`
3. See no result

**Expected behavior**

Return tag "kubernetes", like search tags in "ask question" page

**Comment by kelvinkuo** [comment]
Where can you set the 'synonym' relation ? I haven't seen this feature.

**Comment by fenbox** [comment]
@kelvinkuo You can set it in the tag info page.
