### ISSUE TITLE
Incorrect display of operator in history when deleting questions in the admin

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#596]
**To Reproduce**
1. Go to Admin -> Contents -> Questions
2. Click on 'delete question'
3. The operator in question history was question owner

**Expected behavior**
The operator in question history was the admin

**Comment by kelvinkuo** [comment]
Where can you see the history of question after it has been deleted?

<img width="1399" alt="image" src="https://github.com/apache/incubator-answer/assets/2784354/6ca5da8f-1900-416f-b3b3-2711d7c8c1ed">

**Comment by fenbox** [comment]
@kelvinkuo click the datetime near author.

![image](https://github.com/apache/incubator-answer/assets/360618/45e50b6f-66e8-41e2-9813-42a4b8442066)

**Comment by kelvinkuo** [comment]
<img width="935" alt="image" src="https://github.com/apache/incubator-answer/assets/2784354/930e6794-5546-49a8-96e5-1810b1aa5d5d">

Is this not correct?

**Comment by fenbox** [comment]
@kelvinkuo It fixed in version 1.2.0
