### ISSUE TITLE
Unable to install UI dependencies

### ISSUE THREAD

**Issue by bishopmate** [apache/incubator-answer#602]
Hi guys, when I try to install the UI dependencies by running `pnpm install` following the steps mentioned on this [page](https://answer.dev/docs/development/contributing/frontend/) I am getting this error:

> Lockfile is up to date, resolution step is skipped
Packages: +1454
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 ERR_PNPM_FETCH_401  GET https://repository-private-363209999838.d.codeartifact.us-west-2.amazonaws.com/npm/react-web-shared-components/codemirror/-/codemirror-5.65.0.tgz: Unauthorized - 401
An authorization header was used: Bearer eyJ2[hidden]
These authorization settings were found:
//repository-private-363209999838.d.codeartifact.us-west-2.amazonaws.com/npm/react-web-shared-components/:_authToken=eyJ2[hidden]
Progress: resolved 1454, reused 0, downloaded 0, added 0

System: Mac Pro M1
Node version: v21.1.0
pnpm version: 8.9.2

Please help!!!

**Comment by bishopmate** [comment]
Hi @LinkinStars, there hasn't been any response from @shuashuai on this and this is assigned to him. Can someone else please help with this?

**Comment by shuashuai** [comment]
I just tested it with the corresponding node and pnpm versions you provided, and everything works fine. From the error message you provided, it looks like there was an error in the authorization information during the installation process, so you can try this command alone
```
pnpm add codemirror@5
```
If this works, then you should also be able to run the project.
If you have other questions, please continue to provide feedback.

**Comment by bishopmate** [comment]
Hi @shuashuai, yes it got resolved. The issue was that I had some registry configuration in my .npmrc file which was being by default.
