### ISSUE TITLE
add details about ASF iCLA and Code of Code to your Contributing guide

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-answer#629]
* https://www.apache.org/licenses/contributor-agreements.html
* https://github.com/apache/.github/blob/main/.github/CODE_OF_CONDUCT.md

It's up to ASF projects to decide if you only merge PRs after you know the contributor has signed a CLA (or their employer has) - or if you only require it on reasonably sized contributions.

**Comment by fenbox** [comment]
Thanks for the feedback, the contributing guide has been updated.

- https://answer.apache.org/community/contributing
- https://answer.apache.org/community/pull-request
