### ISSUE TITLE
The site map has a lot of blank lines causing errors.

### ISSUE THREAD

**Issue by Liamn0244** [apache/incubator-answer#631]
**Describe the bug**
The site map has a lot of blank lines causing errors.

**To Reproduce**
<img width="1399" alt="1" src="https://github.com/apache/incubator-answer/assets/135837370/48b3baf9-0a6a-4f5a-85e3-96d506b2c441">

If the domain is proxied using cloudflare, no problems will be found. But sites that are not using cloudflare will have this problem. Viewing the source code of the website using Google Developer Tools, you can see the presence of extra space lines.

<img width="1908" alt="2" src="https://github.com/apache/incubator-answer/assets/135837370/1c7d4edc-3b5b-4d30-a22e-5b4152373104">

**Comment by sy-records** [comment]
I didn't reproduce your question.

<img width="1166" alt="image" src="https://github.com/apache/incubator-answer/assets/33931153/a8324ab0-a9fe-4b25-ba08-30543ea3cb49">

**Comment by Liamn0244** [comment]
My DB is Postgresql.
These extra blank lines need to be removed.

<img width="813" alt="image" src="https://github.com/apache/incubator-answer/assets/135837370/45bb58f3-9455-4ee2-8c56-ca7f3dbdc89e">

**Comment by sy-records** [comment]
I think I know why. Wait a minute while I test it.
