### ISSUE TITLE
Restrict: users can only write one answer to the same question

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#644]
## Is your feature request related to a problem? Please describe.

Answer is a Q&A platform, not a forum. Some users mistake the answer section for a discussion area. Despite receiving prompts to edit their original answers, they keep adding new answers, breaking down the answer into several separate responses, making it difficult to accept the correct answer.

![image](https://github.com/apache/incubator-answer/assets/360618/c7097885-c97e-432b-aef2-80eedb46ec0d)

## Describe the solution you'd like

By default, users can only write one answer to the same question.

1. Add switch option in `admin -> settings -> write`, default is "On".
   
   ![image](https://github.com/apache/incubator-answer/assets/360618/a83dc71f-80d7-4f99-b3f1-1e258bb9369d)

2. When the user has answered the current question (excluding deleted ones):
   - Show “Edit my existing answer” which takes the user to the page where they can edit their answer.
   - When allowing multiple answers from the same user, display another button “Add another answer”. Clicking on it will prompt a dialog box as before.
   
   ![image](https://github.com/apache/incubator-answer/assets/360618/15176349-7895-4247-99f6-1bead5e7d76f)

Design files: [Answer](https://www.figma.com/file/MeOkbCEQS9jCDRVHcjTRtY/Answer-Core?type=design&node-id=19502%3A2581&mode=design&t=dxM16BHTbgn9TWKy-1), [Settings](https://www.figma.com/file/MeOkbCEQS9jCDRVHcjTRtY/Answer-Core?type=design&node-id=5085%3A4607&mode=design&t=dxM16BHTbgn9TWKy-1)

**Comment by hgaol** [comment]
Hi, I'd like to try this task. thx~

**Comment by fenbox** [comment]
Hi @hgaol, I improved the description. You can give it a try.

**Comment by hgaol** [comment]
Thanks @fenbox . I'm not so familiar with frontend but can have a try. If it's urgent, you can re-assign it to another guy. Or I'll take some time to ramp up. :)

**Comment by b4s36t4** [comment]
Would love to take this up for a try :)

**Comment by fenbox** [comment]
@hgaol Maybe you can write the backend first, and then we'll see if anyone can help write the frontend if we don't have enough time.

**Comment by hgaol** [comment]
Hi @fenbox , sorry for late reply. There's one question that what should we do if there're already more than one answers from same person? Should we show a model to let user select or just randomly select one to edit?

**Comment by fenbox** [comment]
Hi @hg, In order to reduce complexity, I think it would be more appropriate to edit the one that was first posted.
