### ISSUE TITLE
The Question Editor input box does not work with the Grammarly Chrome extension.

### ISSUE THREAD

**Issue by Liamn0244** [apache/incubator-answer#659]
**Describe the bug**
The Question Editor input box does not work with the Grammarly Chrome extension.

Grammarly Chrome extension helps us to fix spelling mistakes and grammatical errors. This is a very useful feature. Hope all our input boxes are compatible with this extension.

**Screenshots**
Below is the question input box for GitHub.
<img width="893" alt="image" src="https://github.com/apache/incubator-answer/assets/135837370/e6912bdc-b151-4571-a3a0-c8137b96efa5">

**Comment by shuashuai** [comment]
Our editor uses [codemirror5](https://codemirror.net/5/). According to the documentation, codemirror currently does not provide support for this type of spell check plug-in;

In addition, it is not necessary to support all inputs. Next, we will support plug-ins such as spell check in input boxes related to question writing or editing.
