### ISSUE TITLE
Disable unlisted post from showing up in profile and search engines

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#661]
## Currently

- Unlisted posts still shows in user profile.
- Unlisted posts can be indexed by search engine.

## Expectation

- Hide unlisted posts in user profile from other users.
- Post author, Admin, Moderator still can see.
- Block Search indexing with [`noindex`](https://developers.google.com/search/docs/crawling-indexing/block-indexing).

**Comment by insistedMarin** [comment]
Hello, i am new here, and i would like try to solve this problem. In fact, I have partially fixed the display problem of the user profile. But for the search problem of unlisted posts, it worked fine in my tests. Has this problem been fixed? Also, please consider assigning this task to me.
