### ISSUE TITLE
Change the starting link

### ISSUE THREAD

**Issue by zeynepozdemir** [apache/incubator-answer#663]
Hello, the initial screen on the website is localhost/questions when it first opens, but I want it to be localhost/tags. What can I do? Where should I make changes in the code? Can you help me with this?

**Comment by shuashuai** [comment]
If you want to modify the source code, you can modify the ui/src/router/routes.ts file; just change this option
```
{
  index: true,
  page: 'pages/Questions' // Home page is question
}

//  modify the above to
{
  index: true,
  page: 'pages/Tags' // Home page is tag
}

```
