### ISSUE TITLE
[UI] Theme color setting bugs

### ISSUE THREAD

**Issue by ty114514** [apache/incubator-answer#673]
**Describe the bug**
1. Change the site color to white, some buttons will hide in the background because they don't have borders or are darker than the background
2. There is no default blue on the color panel

**Comment by shuashuai** [comment]
Our UI system uses [bootstrap](https://getbootstrap.com/docs/5.3/getting-started/introduction/), so changing the theme here actually only changes the [primary color](https://getbootstrap.com/docs/5.3/customize/color/), so some colors cannot reach the contrast of bootstrap.

Users need to be aware of the possible effects when using it！

**Comment by ty114514** [comment]
I know, but when I looked at the bootstrap example you sent, I found that their light color buttons are different from the white background
Also the primary blue doesn't seem to be in the panel, I've tried switching back but nothing is consistent with it

**Comment by shuashuai** [comment]
As I've mentioned above, our theme color just modifies the --bs-primary color, while the light color is the bootstrap built-in --bs-light color. The two are not equivalent, which means that these theme colors are built-in and ours just modifies the primary color to the corresponding color! Also, I tried modifying the theme color and then changing the theme color to the default color. It is modifiable. If you didn't succeed, please describe your modification steps in detail.

**Comment by ty114514** [comment]
The results tested on Firefox do not seem to be the same in other browsers.

https://link.storjshare.io/s/jwv7dmfnqha3soxabiccitgbnimq/dc5cb556-bb0e-44d5-9506-01b94d9592f8%2Flv_0_20231219123825.mp4

**Comment by shuashuai** [comment]
This is a bug caused by the compatibility of different browsers with input type=color. After discussion, we decided not to do special processing for the time being. If this problem occurs, you can use a PC browser to adjust the color!
