### ISSUE TITLE
After setting the tag as a synonym, the questions do not show under the origin tag.

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#680]
**To Reproduce**

1. Two questions:
   - Question A with tag "k8s"
   - Question B with tag "kubernetes"
2. Set "k8s" as a synonym for "kubernetes".
3. Question A do not show under "kubernetes" tag.

**Expected behavior**

Question A show under "kubernetes" tag.

**Comment by hgaol** [comment]
Hi, I'd like to fix this issue, and will submit PR later.

**Comment by fenbox** [comment]
Thank you, looking forward to it.
