### ISSUE TITLE
Hope to optimize the page UI

### ISSUE THREAD

**Issue by shenchunyu** [apache/incubator-answer#688]
![Snipaste_2023-12-20_00-58-15](https://github.com/apache/incubator-answer/assets/37767682/92445986-754a-47a1-9041-55b6222e77ef)

![Snipaste_2023-12-20_01-00-08](https://github.com/apache/incubator-answer/assets/37767682/998c2720-031d-4b1c-b5ad-e0c8674f746a)
![Snipaste_2023-12-20_01-00-36](https://github.com/apache/incubator-answer/assets/37767682/fbf712dc-3d2f-4050-a520-2d0a9f8a3411)

**Comment by fenbox** [comment]
Please describe a clear and concise description of what the problem is.
