### ISSUE TITLE
Tags with special characters

### ISSUE THREAD

**Issue by mortenbirkelund** [apache/incubator-answer#692]
**Describe the bug**
Special characters in tags causes answer to assume incorrect urls. For instance a forward slash will be accepted in the tag, which obviously causes a problem in a url

**To Reproduce**
1. Create a tag with a forward slash "Something / something"
2. See that the url that answer uses for the tag is https://yourdomain/tags/Something-/-something
3. Try and visit this url, and you will get a 404

**Expected behavior**
I expected that answer will either not allow special characters when creating tag, or would url-encode before creating the url. 

**Screenshots**
NIL

**Comment by shuashuai** [comment]
In response to this situation, we have made a repair in V1.2.1, and special characters will be escaped in 1.2.1. this version will be released soon.

In 1.2.1, the url will be displayed like this `/tags/something-%2F-something`.

**Comment by sy-records** [comment]
While escaping works, it doesn't seem to match the prompt message.

https://github.com/apache/incubator-answer/blob/82fdfc77636d8d1ce28710d929a8c22bb52834ef/i18n/en_US.yaml#L733-L735

**Comment by fenbox** [comment]
@sy-records May be we need remove the prompt message.

**Comment by shuashuai** [comment]
> While escaping works, it doesn't seem to match the prompt message.
> 
> https://github.com/apache/incubator-answer/blob/82fdfc77636d8d1ce28710d929a8c22bb52834ef/i18n/en_US.yaml#L733-L735

We ignored the prompt message for editing the tag when modifying the condition. The latest news should be

![image](https://github.com/apache/incubator-answer/assets/30591202/f0405479-13cb-46e4-80f2-65db05940bfa)

The prompt message you marked should be consistent with the above. Maybe you can help us fix the prompt message!
