### ISSUE TITLE
Customize privileges required reputation

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#695]
## Current

There are three levels.

![Image](https://github.com/apache/incubator-answer/assets/360618/d652d06d-0b8a-4219-b1ff-03a0f464217c)

## Expect

Add a `Custom level`. Admin can set any number greater than `0`.

**Comment by hgaol** [comment]
Hi @fenbox , if no started, I'd like to try this task. Thanks!

**Comment by fenbox** [comment]
@hgaol Thank you. Looking forward to it.
