### ISSUE TITLE
Display the number of unexpanded comments

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#705]
## Current

- Show the top 3 comments with the highest votes, sorted by votes from high to low
- If the votes are the same, then sort by the posting time from old to new as the second criteria
- Click on "Expand Comments" to see the more comments
- After expanding, the comments are re-sorted by posting time from old to new, and load 15 comments at a time

## Expect

- When there are less than 3 comments, display them in order of posting time from old to new
- When there are more than 3 comments
  - Prioritize showing the top 3 comments with the highest votes, sorted by votes from high to low
  - If the votes are the same, then sort by posting time from old to new as secondary criteria
  - Display a "100 more comments" button, with "100" representing the remaining comments
  - After clicking, the comment list will be re-sorted by posting time from new to old, and load 15 comments at a time

![Image](https://github.com/apache/incubator-answer/assets/360618/70448b4b-5a18-407e-8da3-40e482e2b8bc)

**Comment by insistedMarin** [comment]
hello，i'd like try to solve this problem.

**Comment by fenbox** [comment]
@insistedMarin Thank you. Looking forward to it.
