### ISSUE TITLE
Improve invite people to answers

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#710]
## Current

The operation steps of request answers are complicated.

Edit -> click "Add people" -> Select people -> Save -> Done

![Image](https://github.com/apache/incubator-answer/assets/360618/3693e5b3-941a-4e4e-ba92-aed9cc0df616)

## Expect

Like add assignees in GitHub issue.

Edit -> Select people -> Done

![Image](https://github.com/apache/incubator-answer/assets/360618/ff54b941-aea3-480d-b1d7-889a223fd262)

**Comment by surapuramakhil** [comment]
@fenbox how can I access this feature?. I couldn't see this option in current edit.

Current Edit of Question:
![image](https://github.com/apache/incubator-answer/assets/9161543/a59a74d4-b297-4e38-8eca-e85178a42aa3)

**Comment by fenbox** [comment]
@surapuramakhil it's in question detail page.

![image](https://github.com/apache/incubator-answer/assets/360618/158f04f2-9981-4c96-ab60-c85a9523cb8e)

**Comment by surapuramakhil** [comment]
@fenbox ah box title and description is not matching over there.

Created this https://github.com/apache/incubator-answer/issues/849
