### ISSUE TITLE
Add the previous button on the install page

### ISSUE THREAD

**Issue by jihuayu** [apache/incubator-answer#716]
## Is your enhancement request related to a problem? Please describe

The installation interface only has a "Next" button and does not have a "Previous" button.
When I realized that I had made a configuration mistake, I was unable to go back to the previous step to modify the settings I had already configured.
![image](https://github.com/apache/incubator-answer/assets/32858525/a83d730e-eb40-4531-9640-b3cf6834452f)

## Describe the solution you'd like

Add the previous button on the install page.

## Describe alternatives you've considered

none

**Comment by fenbox** [comment]
For security reasons, the config.yaml file cannot be modified after it has been created.

You can delete it and reinstall it.
