### ISSUE TITLE
Make build fails

### ISSUE THREAD

**Issue by surapuramakhil** [apache/incubator-answer#734]
## Describe the bug

cloned repo - followed documentation installed all pre-requisite

when I run make build command below is the output

```sh
akhil@Akhil-S:~/startup/incubator-answer$ make build
wire: github.com/apache/incubator-answer/cmd: wrote /home/akhil/startup/incubator-answer/cmd/wire_gen.go
internal/service/siteinfo_common/siteinfo_service.go:33: running "mockgen": exec: "mockgen": executable file not found in $PATH
make: *** [Makefile:28: generate] Error 1
``` 

### Screenshots

If applicable, add screenshots or video to help explain your problem.

### Platform

Not UI / app related issue.  build related issue.
using WSL - ubuntu

- Device: [e.g. Desktop, Mobile] 
- OS: [e.g. macOS]
- Browser and version: [e.g. Chrome, Safari]
- Version: [e.g. v1.2.0]

**Comment by surapuramakhil** [comment]
Is this supposed to run only from docker container?

**Comment by zahash** [comment]
i had this same issue.

you also need to add /home/<your_username>/go/bin  to your path
this is where go keeps all the installed binaries
you can find the mockgen binary there

i think you only added the path where go was installed.
