### ISSUE TITLE
Why does the system get reset every once in a while?

### ISSUE THREAD

**Issue by qianmoQ** [apache/incubator-answer#739]
## Describe the bug

Why is the system reset (restored to initialized system) every once in a while? This will cause the system to become inaccessible. The system will be restored after 5 or 6 minutes, and no error message will appear in the log. Is there a scheduled task running?

### Screenshots

If applicable, add screenshots or video to help explain your problem.

### Platform

- Device: [e.g. Desktop, Mobile]
- OS: [e.g. macOS]
- Browser and version: [e.g. Chrome, Safari]
- Version: [e.g. v1.2.0]

**Comment by fenbox** [comment]
@LinkinStars Can you please guess the possible reasons for this? It seems to be very rare.
