### ISSUE TITLE
Do not contact answer.dev automatically

### ISSUE THREAD

**Issue by frafra** [apache/incubator-answer#764]
## Is your enhancement request related to a problem? Please describe

I deployed Answer and I get this error: `ERROR	dashboard/dashboard_service.go:219	request remote version failed: Get "https://getlatest.answer.dev/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`. This happens because Answer try to reach `answer.dev`, but the firewall does not allow internal services to contact external resources, by default.

## Describe the solution you'd like

It would be nice to check the version only when requested or enabled.

## Describe alternatives you've considered

Ignore the error messages.

**Comment by fenbox** [comment]
Add option in settings -> general

![image](https://github.com/apache/incubator-answer/assets/360618/11e75a77-076c-41af-a3bc-021a2bc8806f)

**Comment by hgaol** [comment]
Hi @fenbox , if not assigned, I'd like to work on it. thx!
