### ISSUE TITLE
Incomplete text display when pasting text into the tags field

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#773]
## Describe the bug

Paste the copied text to the tags field in ask question page, the word display is incomplete.

![image](https://github.com/apache/incubator-answer/assets/360618/de8c77cd-1805-4070-9142-f1b349047bf7)

If you use the keyboard to type letter by letter, it can be displayed in its entirety.

![image](https://github.com/apache/incubator-answer/assets/360618/fa98a958-6893-4646-be53-aabe4b3906b9)

### Expected behavior

Show full characters when pasted.

### Platform

- Device: Desktop
- OS: macOS
- Browser and version: Chrome
- Version: v1.2.5-RC2

**Comment by hgaol** [comment]
Hi @fenbox , I'd like to fix this issue and have submitted a PR.
