### ISSUE TITLE
Input String filters for Language control of users

### ISSUE THREAD

**Issue by surapuramakhil** [apache/incubator-answer#781]
## Is your feature request related to a problem? Please describe
Sometimes Users uses words which are supposed to use in public, Mostly offensive words which add a lot of work for reviewers.

Note: This is practically seen cases. 

## Describe the solution you'd like

Let fronted do simple word filter. if user input text has any offensive words then don't let them submit.

**Comment by fenbox** [comment]
We are renovating the [Review Center](https://github.com/apache/incubator-answer/issues/608) to support users in creating custom review plugins. This issue can be considered for future plugin requirements.

**Comment by surapuramakhil** [comment]
Gotchu. Does anti-spam plugin FW code (interface methods)  provide control at both levels? I mean at frontend level and backend level

**Comment by surapuramakhil** [comment]
created this https://github.com/apache/incubator-answer-plugins/issues/81
