### ISSUE TITLE
Data Inconsistency issue - Sometimes user reputation doesn't change to 1 after activation

### ISSUE THREAD

**Issue by surapuramakhil** [apache/incubator-answer#782]
## Describe the bug

it's been noticed that when user have signed up. Some of them have zero reputation instead of 1

### Screenshots

If applicable, add screenshots or video to help explain your problem.

### Platform

- Device: [e.g. Desktop, Mobile]
- OS: [e.g. macOS]
- Browser and version: [e.g. Chrome, Safari]
- Version: [e.g. v1.2.0]

**Comment by surapuramakhil** [comment]
@fenbox FYI

**Comment by surapuramakhil** [comment]
observed with sqlite db

**Comment by fenbox** [comment]
If the account is inactive, then their reputation is 0.

**Comment by surapuramakhil** [comment]
can you explain flow of  how an user goes to inactive?

This is what happened. User Signed Up.  User tried explore other sections without finishing activation. (user became inactive). User then done activation via activation mail (Now still user reputation is zero, that a problem)

**Comment by fenbox** [comment]
> This is what happened. User Signed Up. User tried explore other sections without finishing activation. (user became inactive). User then done activation via activation mail (Now still user reputation is zero, that a problem, user can't do anything on app. they can't post question, then can't answer, they can't comment)

What's your Answer version?

After the mail is activated, the reputation should go from 0 to 1, and the case where it's still 0 may be something we need to reproduce.

**Comment by surapuramakhil** [comment]
tag: v1.2.5-RC2

> > This is what happened. User Signed Up. User tried explore other sections without finishing activation. (user became inactive). User then done activation via activation mail (Now still user reputation is zero, that a problem, user can't do anything on app. they can't post question, then can't answer, they can't comment)
> 
> What's your Answer version?
> 
> After the mail is activated, the reputation should go from 0 to 1, and the case where it's still 0 may be something we need to reproduce.

**Comment by surapuramakhil** [comment]
@LinkinStars can you try messing (hacking) with account before activation. something like before activating go to other sections of page something like like add question (doing stuff which inactive user can't do)

**Comment by surapuramakhil** [comment]
PS note: I have tired doing repro in answer meta, I wasn't able to do that repro again. this time I got reputation as 1. 

I guess its fine as long as number of cases is reasonable
