### ISSUE TITLE
formatting is effected while pasting content in the Question Body

### ISSUE THREAD

**Issue by surapuramakhil** [apache/incubator-answer#786]
## Describe the bug

Content at source:
![image](https://github.com/apache/incubator-answer/assets/9161543/e94d4a32-bafb-45a9-a2e5-d7585c99b32c)

Content at answer meta when i pasted it
![image](https://github.com/apache/incubator-answer/assets/9161543/ce3fac37-044e-4884-96e5-9eef94c057af)

### Screenshots

If applicable, add screenshots or video to help explain your problem.

### Platform

- Device: [e.g. Desktop, Mobile]
- OS: [e.g. macOS]
- Browser and version: [e.g. Chrome, Safari]
- Version: [e.g. v1.2.0]

**Comment by shuashuai** [comment]
Our editor uses markdown syntax. When copying, it will only recognize the copied text and will not retain the format of the text, such as h1, ul>li, etc. The text contents such as spaces and line breaks will be retained.

Our editor uses the [codemirrow5](https://codemirror.net/5/) implementation.

Content at source:

![image](https://github.com/apache/incubator-answer/assets/30591202/eaf7d1be-60d8-4f94-997f-37fa6261a223)


Content at answer meta when i pasted it:

![image](https://github.com/apache/incubator-answer/assets/30591202/350b295e-054c-4357-901a-0dd1954bddf9)

**Comment by surapuramakhil** [comment]
@shuashuai can you try doing same from AI chatbots? something like perplexity AI etc

**Comment by shuashuai** [comment]
> @shuashuai can you try doing same from AI chatbots? something like perplexity AI etc

There are currently no plans to use AI to handle content format issues. In the future, AI may be used to conduct integrated searches for community content, perhaps like a community chatbot.
