### ISSUE TITLE
Low Scores on page speed insights

### ISSUE THREAD

**Issue by hbsciw** [apache/incubator-answer#787]
I received low scores on [PageSpeed Insights](https://pagespeed.web.dev/) for both my domain and meta.answer.dev. Do you have any suggestions for improving performance?

![Screenshot 1402-11-26 at 17 08 15](https://github.com/apache/incubator-answer/assets/7039555/c7712f94-7e5f-466d-9d02-88c55eb848b9)

![Screenshot 1402-11-26 at 17 08 36](https://github.com/apache/incubator-answer/assets/7039555/b681678c-ebac-41dd-b553-80ebc695338a)

**Comment by surapuramakhil** [comment]
I think the issue is with production builds. do checkout the issue i have raised https://github.com/apache/incubator-answer/issues/784

**Comment by fenbox** [comment]
The [CDN plugin](https://github.com/apache/incubator-answer-plugins/tree/main/cdn-s3) can now be installed to improve the score.
