### ISSUE TITLE
Captcha As Plugin

### ISSUE THREAD

**Issue by surapuramakhil** [apache/incubator-answer#797]
## Is your feature request related to a problem? Please describe

Current Captcha is good. it does a great job of defense but at the same time. it pops up a lot to users. Admins can use captcha of their choice would be great based on their user feedback.

## Describe the solution you'd like
Captcha As Plugin - is Just a suggestion. 
Solution is Admins having a choice of selecting their preferred captha. Just has how OAuth is provided now.

**Comment by fenbox** [comment]
It's a good suggestion. To prevent attacks, it can be enabled by default.
