### ISSUE TITLE
Search Displaying Same items 3 times

### ISSUE THREAD

**Issue by surapuramakhil** [apache/incubator-answer#798]
## Describe the bug

Site tested: https://meta.answer.dev/

I am not sure it it is a design Bug or UI bug.  when I searched for unDelete keyword I got 3 results of same page / post (its due 1 question & 2 answers) . UI for each item is same but what it differed is the place where I land on page. 1 lands at question and other 2 land of each one of the answer

![image](https://github.com/apache/incubator-answer/assets/9161543/1b4ba40b-566b-413b-8992-79d49e7b7b24)

### Screenshots

If applicable, add screenshots or video to help explain your problem.

### Platform

- Device: [e.g. Desktop, Mobile]
- OS: [e.g. macOS]
- Browser and version: [e.g. Chrome, Safari]
- Version: [e.g. v1.2.0]

**Comment by surapuramakhil** [comment]
Oh that info requires too much attention to detail. 

But here is my point. (think as a user perspective or you as a user searching for questions with particular text) the word I am searching for is unDelete. I get 3 results with the same line where my interest word is there. Its same question.

Even if you dig deeper or have very close attention to detail. why for same question - one line items say 2 answers and other two as zero answer. Also zero answer marking is not same other two. (I understand why its happening) 

that's why I have said - Not sure its Design bug / UI bugs /  code bug.

**Comment by fenbox** [comment]
> Even if you dig deeper or have very close attention to detail. why for same question - one line items say 2 answers and other two as zero answer. Also zero answer marking is not same other two. (I understand why its happening)

Hi @surapuramakhil, I think the "two as zero answer" is a Bug.

For answers, only display the votes number. If it has been accepted, display the acceptance status.

![image](https://github.com/apache/incubator-answer/assets/360618/56264ed3-6ad8-4043-9b3c-1c011fc02295)

**Comment by surapuramakhil** [comment]
@fenbox can you consider highlighting  **"matched words to user input"**
