### ISSUE TITLE
Fail to Paste Hex Color Code

### ISSUE THREAD

**Issue by PrimmaAnna** [apache/incubator-answer#802]
## Describe the bug

I was trying to copy and paste the color code to change the theme of my Answer and it didn't work.

### To Reproduce

1. Go to 'Admin'
2. Click on 'Customize - Themes'
3. Scroll down to 'Primary Color'
4. Switch to HEX. 
5. Copy and paste the code. 

### Expected behavior
The code can be pasted and saved.

### Screenshots

https://github.com/apache/incubator-answer/assets/131739771/fdd6e9a3-aea6-4ec1-8a64-097fbf36e503

### Platform

- Device: [Desktop]
- OS: [e.g. macOS]
- Browser and version: [e.g. Chrome]
- Version: [e.g. v1.2.5]

**Comment by fenbox** [comment]
I'm sorry, but I'm afraid this is a problem with the Chrome's native controls. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color
