### ISSUE TITLE
Incorrect display of answers in search results

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#803]
For answers, only display the votes number. If it has been accepted, display the acceptance status.

![image](https://github.com/apache/incubator-answer/assets/360618/56264ed3-6ad8-4043-9b3c-1c011fc02295)

_Originally posted by @fenbox in https://github.com/apache/incubator-answer/issues/798#issuecomment-1963274610_

**Comment by hgaol** [comment]
Hi @fenbox , I'd like to fix this issue if not assigned yet.
