### ISSUE TITLE
When an administrator accesses a deleted question, the delete button still displayed

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#813]
## Describe the bug

![image](https://github.com/apache/incubator-answer/assets/360618/a315bbb2-6c68-4aa0-9c46-346546a1461b)

When an administrator accesses a deleted question, the delete button still displayed.

### Expected behavior

The delete button should no longer be displayed

### Platform

- Device: Desktop
- Version: v1.2.5

**Comment by hgaol** [comment]
Hi @fenbox , I'd like to fix it.
