### ISSUE TITLE
Getting Error, TAG not found. When site settings don't require tags for question creation.

### ISSUE THREAD

**Issue by surapuramakhil** [apache/incubator-answer#815]
## Describe the bug

![image](https://github.com/apache/incubator-answer/assets/9161543/9d2d19fb-6656-47b4-8e33-2668e74bafde)

**Same error will be received irrespective of this settings**
![image](https://github.com/apache/incubator-answer/assets/9161543/5e209cb0-4d76-4536-9d15-12d89182ce37)

### Expected behavior

You should be able to post your question without any tags. When settings are configured.

### Screenshots

If applicable, add screenshots or video to help explain your problem.

### Platform

- Device: [e.g. Desktop, Mobile]
- OS: [e.g. macOS]
- Browser and version: [e.g. Chrome, Safari]
- Version: [e.g. v1.2.0]

**Comment by surapuramakhil** [comment]
Oh, then it's a strong **design bug**. After your text I went back and understood what it is.

Actually, this part of the setting page has three sections. which **I totally didn't understand until I read your message**. 

![image](https://github.com/apache/incubator-answer/assets/9161543/56a78614-630b-4a18-81ed-9713b3447b4e)



I always thought based on UI it has two sections that's what UI layout says to the users. something like this
![image](https://github.com/apache/incubator-answer/assets/9161543/92121b9d-466a-47ec-afd7-6eef1457207c)

**Comment by surapuramakhil** [comment]
maybe a line break after section would help in understanding. @fenbox

**Comment by fenbox** [comment]
Thank you, and we will try to improve.

**Comment by fenbox** [comment]
I tried to make some changes, maybe this way won't be confusing.?

![image](https://github.com/apache/incubator-answer/assets/360618/62d0d0c1-c296-4739-ae1b-57d1011e9066)

**Comment by surapuramakhil** [comment]
it's still the same. Notice the repeated UI portion (it's a toggle button & multi select input) its repeated, it makes interpretation to user that there are two sections and that's what defines section from UI perspective. 

Does this have 3 or 4 sections? if four then I would suggest changing order,

suggested order as an example

1. Restrict write
2. set required tags
3. recommended tags
4. reserved tags

so that UI doesn't give false intentions

if its three sections
I think just having a line after each section would be sufficient.

**Comment by fenbox** [comment]
It's four sections.

![image](https://github.com/apache/incubator-answer/assets/360618/c616f1e2-f93e-4406-bca0-187e60667bc6)

**Comment by surapuramakhil** [comment]
One issue I could see is for item 2. The name/title says "Set Required Tags" but its description says "set recommend tags as required tags". Title and description are not matching. 

I would suggest this order:
1. Reserved Tags
2. Recommended Tags
3. Set Recommended tags as Required (title and description should match for this item)
4. Answer write

**Comment by fenbox** [comment]
![Image](https://github.com/apache/incubator-answer/assets/360618/18bd82b3-51c1-4325-adb6-309a9615d7aa)
