### ISSUE TITLE
Linking question similar to GitHub issues

### ISSUE THREAD

**Issue by surapuramakhil** [apache/incubator-answer#817]
## Is your feature request related to a problem? Please describe

Linking question similar to GitHub issues. Ability for user to link question while posting. Connection/link visibility on both questions

**Comment by sosyz** [comment]
Hi @fenbox! I was wondering if there have been any updates on this issue? I'm interested in this feature and would love to be assigned to it.

**Comment by shuashuai** [comment]
Sorry for the late reply, who of you two is willing to contribute to this issu?

@bangzzzz  @sosyz

**Comment by sosyz** [comment]
> Sorry for the late reply, who of you two is willing to contribute to this issu?
> 
> @bangzzzz @sosyz

If @bangzzzz doesn't have time, I can take it.

**Comment by fenbox** [comment]
Hi @sosyz, I updated some ideas.

When question A references the link of question B, A will be associated as a backlink to B and displayed on the page of question B.

- **Establish link under following conditions**:
  - When question A is approved and in normal status
    - The content includes a link to question B (either a question or an answer)
    - OR an approved answer contains a link to question B (either a question or an answer)
  - When question A is closed
    - The closure reason includes a link to question B (either a question or an answer)

- **Remove link under following conditions**:
  - When question A is deleted
  - When question A is in normal status
    - The content and answers no longer contain a link to question B (either a question or an answer)
    - OR all answers containing a link to question B are deleted

**Other rules**:
  - Display up to 5 posts, sorted by question popularity
  - Click "More" to visit "all linked questions" page


**Design file**:

- [Linked sections](https://www.figma.com/design/MeOkbCEQS9jCDRVHcjTRtY/Answer-Core?node-id=88-472&t=ThKWBdYEX2pxbWm3-4)
  
  ![image](https://github.com/user-attachments/assets/2c8f5fce-d7e6-4e37-aa70-6b5a9ad8282e)

- [All linked questions page](https://www.figma.com/design/MeOkbCEQS9jCDRVHcjTRtY/Answer-Core?node-id=24373-7193&t=ThKWBdYEX2pxbWm3-4)
  - path: `/questions/linked/question_id`
  - title: `Linked Questions - {{ site_name }}`

  ![image](https://github.com/user-attachments/assets/7e1900e8-ead8-437b-9867-3f339ba1ab3e)

**Comment by sosyz** [comment]
@fenbox Thank you very much! The design diagram has been incredibly helpful for me. Displaying related issues on the sidebar would be a more suitable way for viewing them, I’ll follow the design to implement it.

Currently, I’m working on supporting associations via hashtags (e.g., starting with `#`) or question links. Do you have any suggestions for this part? Perhaps we need to add some hidden payload to prevent accidental links?

**Comment by fenbox** [comment]
> supporting associations via hashtags (e.g., starting with #) or question links

I agree and have no suggestions for now.

> Perhaps we need to add some hidden payload to prevent accidental links?

[I couldn't find some public information](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#issues-and-pull-requests), but I think there may need to be some restrictions to prevent attacks through this feature. For example, if a post contains the IDs of all posts, it may affect the website's performance when published.

**Comment by sosyz** [comment]
Got it~ I will be mindful of this potential risk.
