### ISSUE TITLE
Username Search Returning No Results

### ISSUE THREAD

**Issue by PrimmaAnna** [apache/incubator-answer#819]
## Describe the bug
I try to search the user name in Answer, but failed.

### To Reproduce

1. Click Search.
2. Input: user:username.
3. No results shown.

### Expected behavior
Show posts, answers created by the user.

### Screenshots

https://github.com/apache/incubator-answer/assets/131739771/e2c21501-7c8d-4998-aa52-137c2099a353

### Platform

- Device: Desktop
- OS: macOS
- Browser and version: Chrome
- Version: 121.0.6167.85

**Comment by hgaol** [comment]
Hi @PrimmaAnna , I'd like to fix this issue.

**Comment by surapuramakhil** [comment]
Can someone update Apache answer docs - https://answer.apache.org/docs/ about features set of Apache answer?

@fenbox doing at time of release (adding features) would be great option. At least can you add this as issue in https://github.com/apache/incubator-answer-website and open source community can update it.
