### ISSUE TITLE
Init command with custom port 

### ISSUE THREAD

**Issue by bestony** [apache/incubator-answer#827]
## Is your feature request related to a problem? Please describe

Yes, If i run nginx local, i can't init answer with default config

## Describe the solution you'd like

user can init answer with custom prompt (not just data dir)

## Describe alternatives you've considered

- add new flag for custom port
- add feature only init file. don't try to start answer, let people change config ,and the start by manual.
- add feature to load a full config file.

**Comment by calmdev** [comment]
You could use something like [yq](https://github.com/mikefarah/yq) to change it to an alternate port:
```
yq -i '.server.http.addr="0.0.0.0:3200"' ./answer-data/conf/config.yaml
```
Then start answer:
```
./answer run -C ./answer-data/
```
