### ISSUE TITLE
Basic Connector Overrides profile picture

### ISSUE THREAD

**Issue by surapuramakhil** [apache/incubator-answer#857]
For an existing account where user has already set his profile picture. A login using connector will override profile picture.

Ideal:
Profile picture should be taken from connector only if the user hasn't set his picture.

**Comment by Octobug** [comment]
@surapuramakhil  @LinkinStars  It is possible to setup Google or GitHub connect process in development? I tried these two providor but both ended up /50x page 😂

**Comment by surapuramakhil** [comment]
Yes, it is.

I actually stated with Google connector, but facing this https://github.com/apache/incubator-answer-plugins/issues/65


- https://github.com/apache/incubator-answer-plugins/tree/main/connector-basic#google-oauth-configuration-example
- https://meta.answer.dev/questions/D1ka/setting-up-answer-docker-with-google-sign-in


I have fallen back to basic connector as per this comment https://github.com/apache/incubator-answer-plugins/issues/65#issuecomment-1950998532


Try using basic connector, it works for sure.

**Comment by Octobug** [comment]
> Yes, it is. It is possible to set up Google or GitHub connect process in development.
> 
> I actually stated with Google connector, but facing this [apache/incubator-answer-plugins#65](https://github.com/apache/incubator-answer-plugins/issues/65)
> 
> * https://github.com/apache/incubator-answer-plugins/tree/main/connector-basic#google-oauth-configuration-example
> * https://meta.answer.dev/questions/D1ka/setting-up-answer-docker-with-google-sign-in
> 
> I have fallen back to basic connector as per this comment [apache/incubator-answer-plugins#65 (comment)](https://github.com/apache/incubator-answer-plugins/issues/65#issuecomment-1950998532)
> 
> Try using basic connector, it works for sure.

@surapuramakhil 

Thank you! I'll try the basic connector later. I also encountered this "does not provide a unique UserID" problem and I thought maybe it only happened in development for there being a frontend port and a backend port.
