### ISSUE TITLE
Account setting label issue

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#881]
## Describe the bug

![image](https://github.com/apache/incubator-answer/assets/360618/8c688fb2-65d7-4146-9e9b-a4746293ae72)

This is the current email, not the new email.

### To Reproduce

Visit /users/settings/account

### Expected behavior

Change label text from "New email" to "Email".

### Platform

- Version: v1.2.5

**Comment by sy-records** [comment]
Can you assign this to me?
