### ISSUE TITLE
Add reactions to question & answer

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#883]
## Summary

We are thinking about adding a reaction feature to:

1. Increase interaction among users
2. Reduce meaningless comments.

This is because the community's voting system has reputation thresholds and limited usage scenarios. Reactions will not affect reputation.

### Task 1

- [ ] Change "Add a comment" button style, like [`btn-light`](https://getbootstrap.com/docs/5.3/components/buttons/#variants) with small size and pill style

![image](https://github.com/apache/incubator-answer/assets/360618/cc4c44ca-8e04-4e08-a1ae-3f346f6cebf8)

### Task 2

- [ ] Add reactions

![image](https://github.com/apache/incubator-answer/assets/360618/e67b722b-9b11-42a2-9071-6e428a33f877)

**Rules**

- All actived user can add reaction, like github issue.
- Reaction include:
  - Emoji: heart, smile, frown
  - Response count: Users who added on that emoji
- When moving to an existing reaction, show which people clicked on that emoji, display the first 5 users and "{{n}} more..." for the rest.
- When clicking on an existing emoji, that emoji +1.
- Clicking on the `+` shows available emojis to choose from, and selecting one will increase that reaction count by 1.
- No need for system notifications.
- Reaction does not affect reputation.

## Design files

![image](https://github.com/apache/incubator-answer/assets/360618/ba4edb8b-e208-45c8-adb4-b68f0e9cfe36)

- Figma
  - [Question detail](https://www.figma.com/file/MeOkbCEQS9jCDRVHcjTRtY/Answer-Core?type=design&node-id=88-472&mode=design&t=RFZZrlRg9qtctpJl-4)
  - [Reaction status](https://www.figma.com/file/MeOkbCEQS9jCDRVHcjTRtY/Answer-Core?type=design&node-id=22915-1922&mode=design&t=RFZZrlRg9qtctpJl-4)
- [CoDesign](https://codesign.qq.com/s/vq0rnwDY6wOv303/429lYdBd6N63V0d/inspect), PWD: 7XXV

**Comment by surapuramakhil** [comment]
@fenbox request consider it is for comments to.
As of now, it's thumbs Up (for like) / upvote purposes

**Comment by hgaol** [comment]
Hi @fenbox , I'd like to try this task, thx!

**Comment by fenbox** [comment]
@hgaol Great, I will add more details for development.

**Comment by hgaol** [comment]
About the backend logic, I saw there's `meta` table and the `object_id` column could represent both answer and question. Is it suitable for such scenario? e.g. key is `object.reaction.count`, and value is something like `{"heart": 1, "smile": 1, "frown": 1}`.

Another option is add additional columns in `question` and `answer` tables with these 3 columns, while I don't think altering table is a good thing and it looks little redundant.

Pls let me know if any comment or suggestion, thx! @LinkinStars

**Comment by fenbox** [comment]
> Hi @fenbox , I'd like to try this task, thx!

@hgaol I've updated the details and links to the designs. Contact me if you have any questions.

**Comment by hgaol** [comment]
Hi @LinkinStars , below is my thought in database design. Pls let me know if any comment or suggestion. thx!

About the backend logic, I saw there's `meta` table and the `object_id` column could represent both answer and question. Is it suitable for such scenario? e.g. key is `object.react.summary`, and value is something like `{"heart": [1,2,3], "smile": [3,4,5], "frown": [5,6,7]}`. Here the int array represents the user ids reacted to this emoji.

**Comment by hgaol** [comment]
Hi @fenbox , should it support i18n? e.g. what the Chinese version should be for `smile`, `heart` and `frown`?

**Comment by fenbox** [comment]
> Hi @fenbox , should it support i18n? e.g. what the Chinese version should be for `smile`, `heart` and `frown`?

Yes. 

`simle` -> `笑脸`
`heart` -> `爱心`
`frown` -> `难过`
