### ISSUE TITLE
Handle special characters in site title

### ISSUE THREAD

**Issue by iamdoubz** [apache/incubator-answer#911]
## Is your enhancement request related to a problem? Please describe

I named my site "Iamdoubz Q's". What gets rendered is `Iamdoubz Q&#39;s`.

## Describe the solution you'd like

I would like "Q's" to show instead of `Q&#39;s`.

## Describe alternatives you've considered

I have removed (for the time being) the apostrophe and no more html encoded gibberish.

## Environment
- Ubuntu 20.04
- Apache2 Reverse Proxy
- SystemD startup
- Answer version: `1.3.0 rev 9ebf95c`

**Comment by sy-records** [comment]
Can you assign this to me?
