### ISSUE TITLE
The button miss text in the mobile view

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#916]
## Describe the bug

The button miss text in Admin->Content->Questions in the mobile view.

### Expected behavior

text: More

### Screenshots

![image](https://github.com/apache/incubator-answer/assets/360618/722e50d9-ebec-4b3e-8f91-2da43228dd34)

### Platform

- Device: Mobile
- OS: iOS
- Browser and version: Safari
- Version: v1.3.0

**Comment by zahash** [comment]
@fenbox 

i'll do this

**Comment by zahash** [comment]
@fenbox 

here is the PR https://github.com/apache/incubator-answer/pull/921
