### ISSUE TITLE
Receive irrelevant notifications when editing my own answer

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#924]
### To Reproduce

1. I ask a question
2. Add my answer to this question
3. Edit the answer
4. Receive notification for answer updates

### Expected behavior

I don't need to be notified when I edit my answers.

### Platform

- Device: Desktop
- Version: v1.3.0

**Comment by prithvidasgupta** [comment]
I was able to reproduce the issue. The notification doesn't happen when the question is answered but only when the self answer is updated. I would like to take a crack at it.

**Comment by prithvidasgupta** [comment]
Tested the PR #925 by local build test.

_P.S._ Perhaps a local-run script could be helpful for internal dev ex something like:
```
local-docker-run: build
	@$(DOCKER_CMD) build . --tag apache-answer-test
	@$(DOCKER_CMD) run -d --rm -p 9080:80 -v answer-data:/data --name answer apache-answer-test
```
