### ISSUE TITLE
Some forms have invalid styles that are not as expected

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#927]
## Describe the bug

Some forms missing invalid border style.

- Ask page: body, tags

  ![image](https://github.com/apache/incubator-answer/assets/360618/00f1b917-6b82-4b69-a2b4-fa7b9683a201)

- Answer page
  
  ![image](https://github.com/apache/incubator-answer/assets/360618/f5407b82-3218-49a1-9b17-1b3428aa57a0)

- Comment form

  ![image](https://github.com/apache/incubator-answer/assets/360618/854f67af-01bf-4539-add5-1c9d80cd772e)

### Expected behavior

![image](https://github.com/apache/incubator-answer/assets/360618/d4ab47f3-d32a-4d0d-ac56-14856d598e77)

### Platform

- Version: v1.3.0

**Comment by nayanthulkar28** [comment]
Hi @fenbox ,
New here , trying to make my first contribution. 
Can you assign this issue to me ?
