### ISSUE TITLE
Module not found: Error: Can't resolve '@/plugins' in '/mnt/go/trip/ui/src/utils/pluginKit'

### ISSUE THREAD

**Issue by lvsh2012** [apache/incubator-answer#928]
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Compiled with the following type errors (you may want to check these before deploying your app):

**Module not found: Error: Can't resolve '@/plugins' in '/mnt/go/trip/ui/src/utils/pluginKit'**

on ubuntu system  make ui happen

**Comment by prithvidasgupta** [comment]
I tried running the UI build on the `dev` branch and it worked fine. Which code branch were you on? Can you provide the NodeJS and PNPM version and share if you had some specialized environment?

**Comment by lvsh2012** [comment]
> I tried running the UI build on the `dev` branch and it worked fine. Which code branch were you on? Can you provide the NodeJS and PNPM version and share if you had some specialized environment?

A file was missed during the upload, but the issue has been resolved now. Thank you very much for your help.
