### ISSUE TITLE
when answer's  picture  domain or ipaddress changed

### ISSUE THREAD

**Issue by dddachui** [apache/incubator-answer#930]
Add a picture when I answer, it becomes
! [](http://IPAddress/uploads/post/xxxx.png)
If my domain name or IP address changes, how can I change the IPAddress in the post?

**Comment by dddachui** [comment]
![image](https://github.com/apache/incubator-answer/assets/53245959/7de7975a-0f4d-4629-be28-4f75359beeb9)

**Comment by dddachui** [comment]
can not found ./answer fix

**Comment by dddachui** [comment]
![image](https://github.com/apache/incubator-answer/assets/53245959/485dd35e-f810-430b-a548-f7d79f18e17a)

**Comment by dddachui** [comment]
i am sorry~

**Comment by Octobug** [comment]
> can not found ./answer fix

@dddachui 
I'm still working on it. (I've been a bit busy lately 👀
