### ISSUE TITLE
The review count in the Admin is not correct

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#958]
### To Reproduce

1. A new question in review queue
2. Click <kbd>Reject</kbd> button
3. The question is automatically deleted
4. The review count still show "1" in Admin Dashboard

### Expected behavior

There is no review tasks left. The review count should be "0".

### Screenshots

![image](https://github.com/apache/incubator-answer/assets/360618/0707146d-916e-4715-9ade-813e78c47b51)

![image](https://github.com/apache/incubator-answer/assets/360618/799e417c-475e-43a6-8c92-c684470497b4)

### Platform

- Browser and version: Chrome
- Version: v1.3.1

**Comment by sy-records** [comment]
@LinkinStars  Can you assign this to me?
