### ISSUE TITLE
Click "Follow" on the question page, and the prompt text of the "Follow" button will be displayed on the login box.

### ISSUE THREAD

**Issue by Liamn0244** [apache/incubator-answer#963]
## Describe the bug

Click "Follow" on the question page, and the prompt text of the "Follow" button will be displayed on the login box.

<img width="492" alt="image" src="https://github.com/apache/incubator-answer/assets/135837370/7c23bc41-3440-4233-bcb7-1e831e139c5c">

### Platform

- Device: iPhone 13 (15.1)

**Comment by sy-records** [comment]
Added feature in #943, Have the same problem.

<img width="521" alt="image" src="https://github.com/apache/incubator-answer/assets/33931153/4b2d80cd-7370-4f06-8ca5-4a792c8b7dba">
