### ISSUE TITLE
Google Connector and GitHub Connector have the same ClientID and ClientSecret

### ISSUE THREAD

**Issue by eurooooo** [apache/incubator-answer#968]
## Describe the bug

Google Connector and GitHub Connector show the same ClientID and ClientSecret

### To Reproduce

1. Click Installed Plugins:
![image](https://github.com/apache/incubator-answer/assets/88925843/5d9650fa-fbd6-4ae1-9f65-fae03bb225a1)

2. Click on Google Connector:
![google](https://github.com/apache/incubator-answer/assets/88925843/c246813b-7a7b-451c-becc-af71019da402)

3. Click on Github Connector:
![github](https://github.com/apache/incubator-answer/assets/88925843/384a440f-2918-46c2-b702-3a25d4d827f5)

### Expected behavior

Should show different own ClientID and ClientSecret. 

### Platform

- Device: Desktop
- OS: Windows
- Browser and version: Chrome

**Comment by robinv8** [comment]
Thanks for your feedback, this is indeed a bug and will be fixed in the next version.
