### ISSUE TITLE
The user link in the question details page is not valid

### ISSUE THREAD

**Issue by Liamn0244** [apache/incubator-answer#969]
## Describe the bug
The user link in the question details page is not valid. This link should match the link in the avatar. The link in the avatar is currently correct.

<img width="1056" alt="image" src="https://github.com/apache/incubator-answer/assets/135837370/7669e328-4ad6-4792-bdc0-f19ff7d43252">

**Comment by Liamn0244** [comment]
<img width="964" alt="image" src="https://github.com/apache/incubator-answer/assets/135837370/f66282d8-51d5-4136-9788-e58f65c9fa08">

**Comment by sy-records** [comment]
Fixed via https://github.com/apache/incubator-answer/commit/c6d43e92c196c7d74de13424210bc1f9bbf9c261
