### ISSUE TITLE
Incomplete display of error message alerts on registration page

### ISSUE THREAD

**Issue by fenbox** [apache/incubator-answer#977]
### To Reproduce

1. Go to register page
2. Fill nothing, click on 'Sign up'
3. Show 'email' and 'password' error alert
  
   <img width="350" alt="image" src="https://github.com/apache/incubator-answer/assets/360618/de7259c3-f134-4785-a54e-6ffb565a09ef">

4. Fill 'email' and 'password', click on 'Sign up'
5. Show name 'error' alert
   
   <img width="363" alt="image" src="https://github.com/apache/incubator-answer/assets/360618/6b14d364-ee30-44d0-ad0a-981834d58929">

### Expected behavior

In step 3, 'name' should show error alert too.

### Platform

- Version: v1.3.1

**Comment by hgaol** [comment]
Hi @fenbox , I'd like to fix this issue, thx!
