### ISSUE TITLE
When `@` someone, markdown render error

### ISSUE THREAD

**Issue by kumfo** [apache/incubator-answer#978]
## Describe the bug

When I `@someone` in comment, the generated hyperlink is not parseable properly.

### To Reproduce

the post data like:

```
[@someone](/u/someone)
```

but the result is:

```
<a>@someone</a>
```

### Expected behavior

result must be:

```
<a href="/u/someone">@someone</a>
```

### Screenshots

![20240607-162309](https://github.com/apache/incubator-answer/assets/7692591/f188f6ad-602c-46a0-a548-e37759802f07)

![image](https://github.com/apache/incubator-answer/assets/7692591/10d8402a-a47d-498a-8de8-9538d8f8d601)

**Comment by sy-records** [comment]
Can you assign this to me?
